namespace FolderLocker
{
    public static class Localization
    {
        // Variable global de idioma
        public static string CurrentLang = "ES";

        // =============================================================
        // 1. ESPAÑOL (ES)
        // =============================================================
        #region DICCIONARIO ESPAÑOL (ES)
        private static readonly Dictionary<string, string> ES = new Dictionary<string, string>
        {
            // MENÚ LATERAL
            { "menu_protect", "🔒  PROTEGER" },
            { "menu_unlock", "🔓  ABRIR BÓVEDA" },
            { "menu_files", "📂  MIS ARCHIVOS" },
            { "menu_config", "⚙️ CONFIGURACIÓN" },
            { "menu_manual", "📘  MANUAL DE USO" },
            { "menu_exit", "🚪  SALIR" },

            // HEADER & TABS
            { "title_main", "Centro de Seguridad" },
            { "app_subtitle", "Suite de Seguridad" },
            { "tab_restore", "🔓  RESTAURAR" },

            // PANEL PROTEGER (LOCK)
            { "lbl_target", "CARPETA OBJETIVO (DIRECTORIO A ESCOGER)" },
            { "lbl_pass", "CLAVE DE CIFRADO (CONTRASEÑA)" },
            { "link_forgot", "¿Olvidaste la clave?" },
            { "btn_browse", "Examinar..." },
            { "btn_lock", "INICIAR BLOQUEO" },


            // PANEL RESTAURAR
            { "lbl_path_protected", "RUTA PROTEGIDA ACTUAL" },
            { "btn_decrypt", "DESENCRIPTAR PERMANENTEMENTE" },

            // PANEL MONTAR (VIRTUAL)
            { "title_virtual", "Acceso Virtual Seguro" },
            { "lbl_vaults", "MIS BÓVEDAS (SELECCIONA UNA)" },
            { "lbl_drive", "LETRA DE UNIDAD" },
            { "lbl_mount_pass", "CLAVE DE CIFRADO (CONTRASEÑA)" },
            { "btn_mount", "ABRIR UNIDAD VIRTUAL" },
            { "btn_unmount", "CERRAR UNIDAD" },

            // PANEL SETUP (BIENVENIDA)
            { "setup_title", "BIENVENIDO A LOCKER" },
            { "setup_sub", "Configuración inicial de seguridad." },
            { "setup_lbl_create", "CREA TU CONTRASEÑA MAESTRA" },
            { "setup_lbl_confirm", "CONFIRMA LA CONTRASEÑA" },
            { "setup_note", "⚠️ Recuerda tu usuario y contraseña, Si te llegas a olvidar y sin el código de recuperación,\ntus archivos serán irrecuperables." },
            { "setup_btn", "ESTABLECER SEGURIDAD" },

            // PANEL CONFIGURACIÓN
            { "config_title", "CONFIGURACIÓN" },
            { "config_lbl_lang", "IDIOMA " },
            { "config_chk_start", "Iniciar FolderLocker con Windows (Minimizado)" },
            { "cfg_sec_general", "🌍  GENERAL" },
            { "cfg_sec_system", "💻  SISTEMA" },
            { "cfg_sec_data", "🛡️  PRIVACIDAD Y DATOS" },
            { "cfg_btn_clear", "BORRAR HISTORIAL DE RUTAS" },
            { "cfg_msg_clear", "¿Estás seguro? Se olvidarán las ubicaciones de tus carpetas (no se borran los archivos)." },
            { "cfg_msg_reset", "⚠️ Esto borrará tu cuenta y configuración.\nAsegúrate de haber desencriptado tus carpetas antes de eliminar.\n¿Continuar?" },
            { "cfg_done", "Operación realizada con éxito." },
            { "login_chk_remember", "Recordar Usuario" },
            { "msg_logout_confirm", "¿Cerrar la sesión actual?" },

            // MANUAL
            { "manual_title", "GUÍA RÁPIDA DE USUARIO" },
            { "manual_text", "1. PROTEGER CARPETA:\n   - Ve a la pestaña 'Proteger'.\n   - Elige una carpeta y pon tu contraseña.\n   - La carpeta se ocultará y encriptará.\n\n" +
                             "2. ACCEDER A LOS ARCHIVOS (ABRIR BÓVEDA):\n   - Ve a 'Abrir Bóveda' en el menú lateral.\n   - Selecciona tu carpeta de la lista.\n   - Elige una letra (ej: M:) y pon tu contraseña.\n   - Se abrirá como un disco virtual seguro.\n\n" +
                             "3. RESTAURAR (QUITAR PROTECCIÓN):\n   - Dentro de la pestaña 'Proteger' Esta la opcion de 'Restaurar'.\n   - Selecciona la carpeta a restaurar y pon tu contraseña.\n   - La carpeta volverá a ser normal, la desencriptará y la hará visible.\n\n" +
                             "4. ⚠️ ADVERTENCIAS CRÍTICAS (LEER):\n   - ¡NUNCA entres a la carpeta oculta para pegar archivos manualmente! Se dañarán al intentar desencriptarlos.\n   " +
                                "- Usa la unidad virtual (Letra:) para editar tus archivos. o en cambio desencripta la carpeta, crea, pasa o edita tus nuevos archivos y vuelve a encriptar\n   - NO borres los archivos 'dir.idx' ni 'locker.id', o perderás el acceso a todo.\n   " +
                                "- Si olvidas tu contraseña Y pierdes tu código REC, no hay forma humana de recuperar tus datos.\n   " +
                                "- NO APAGUE el equipo mientras se está protegiendo/restaurando una carpeta grande, podría haber pérdida de datos." },

            // MENSAJES Y ERRORES
            { "msg_select_dir", "Selecciona un directorio a escoger." },
            { "msg_pass_wrong", "Contraseña incorrecta." },
            { "msg_already_list", "Esta carpeta ya está en tu lista." },
            { "msg_rec_title", "Recuperación Inteligente" },
            { "msg_rec_text", "¡Carpeta Recuperada!\nEsta carpeta ya estaba protegida anteriormente.\nSe ha añadido a tu lista sin modificar los archivos." },
            { "msg_lock_success", "Carpeta encriptada y agregada a la bóveda." },
            { "msg_select_restore", "Por favor, selecciona una carpeta." },
            { "msg_confirm_decrypt", "¿Estás seguro de Desencriptar la carpeta\n{0}?" },
            { "msg_decrypt_success", "Carpeta Restaurada exitosamente en:" },
            { "msg_mount_select", "Selecciona la carpeta de la lista." },
            { "msg_mount_active", "Esta carpeta ya está abierta en la unidad {0}" },
            { "msg_drive_busy", "La letra {0} ya está en uso. Elige otra." },
            { "msg_mount_success", "Unidad {0} ACTIVA.\nPuedes acceder desde el menu 'Mis Archivos'." },
            { "msg_unmount_select", "Selecciona en la lista qué carpeta quieres cerrar." },
            { "msg_unmount_success", "Unidad {0} cerrada correctamente." },
            { "msg_unmount_error", "Hubo un problema al intentar desmontar. Verifica que no tengas archivos abiertos." },
            { "msg_no_vault", "No hay ninguna bóveda abierta. Monta una primero." },
            { "err_drag_folder", "Por favor, arrastra una carpeta, no un archivo suelto." },
            { "err_drag_folder_title", "Solo Carpetas" },
            { "msg_mount_select_drive","Selecciona una unidad"},
            { "err_not_owner","⛔ ACCESO DENEGADO\nEsta carpeta pertenece a otro usuario."},
            { "str_0", "Muy Débil" },
            { "str_1", "Débil" },
            { "str_2", "Normal" },
            { "str_3", "Buena" },
            { "str_4", "Fuerte" },
            { "str_5", "Excelente" },
            { "tray_min_title", "FolderLocker Minimizado" },
            { "tray_min_click", "Programa minimizado, click aquí para abrir el programa." },


            // SEGURIDAD CRÍTICA
            { "err_root", "⚠️ ERROR CRÍTICO ⚠️\nEstás intentando bloquear un DISCO ENTERO ({0}).\nEsto corrompería la unidad.\n\nSOLUCIÓN: Crea una carpeta dentro del disco y selecciona esa carpeta." },
            { "err_self", "⛔ AUTO-BLOQUEO EVITADO\nNo puedes bloquear la carpeta donde está instalado el programa." },
            { "err_sys", "⛔ PROTECCIÓN DE SISTEMA\nNo se permite modificar carpetas de Windows." },
            { "err_security_title", "Operación Abortada por Seguridad" },

            // PROGRESO Y TRAY
            { "status_processing", "⏳ PROCESANDO..." },
            { "status_decrypting", "⏳ DESENCRIPTANDO..." },
            { "tray_working", "Locker - Trabajando" },
            { "tray_working_desc", "El proceso continúa en segundo plano. Haz doble clic aquí para ver el progreso." },
            { "tray_done", "Locker - Finalizado" },
            { "tray_done_lock", "La carpeta se ha bloqueado exitosamente." },
            { "tray_done_decrypt", "Carpeta restaurada correctamente." },
            { "tray_minimized_title", "FolderLocker Activo" },
            { "tray_minimized_msg", "La aplicación sigue ejecutándose en segundo plano." },
            { "tray_menu_open", "Abrir Locker" },
            { "tray_menu_exit", "Salir" },

            // UI GENERAL
            { "btn_accept", "ACEPTAR" },
            { "btn_cancel", "CANCELAR" },
            { "btn_yes", "SÍ, CONTINUAR" },
            { "btn_ready", "LISTO" },
            { "prog_title", "PROCESANDO BÓVEDA..." },
            { "prog_init", "Iniciando..." },
            { "prog_hide_btn", "⬇️ Ocultar y trabajar en 2do plano" },
            { "prog_file_lbl", "Procesando: {0}" },
            { "prog_done", "Finalizando..." },
            { "status_done", "¡Hecho!" },

            // VALIDACIONES Y RECUPERACIÓN
            { "title_info", "Información" },
            { "title_confirm", "Confirmar" },
            { "title_error", "Error" },
            { "title_warning", "Advertencia" },
            { "title_success", "Éxito" },
            { "title_security", "Seguridad" },
            { "val_min_chars", "Mínimo 4 caracteres." },
            { "val_no_match", "Las contraseñas no coinciden." },
            { "val_save_code", "GUARDA ESTE CÓDIGO EN UN LUGAR SEGURO:" },
            { "rec_prompt_title", "Recuperación de Cuenta" },
            { "rec_prompt_msg", "Ingrese su Código de Recuperación (REC-XXXX):" },
            { "rec_success_msg", "¡Éxito! Tu contraseña es:" },
            { "rec_fail_msg", "Código incorrecto o inválido." },

            // LOGIN & REGISTRO
            { "login_title", "INICIAR SESIÓN" },
            { "login_lbl_user", "USUARIO" },
            { "login_lbl_pass", "CONTRASEÑA" },
            { "login_btn_enter", "ENTRAR" },
            { "login_btn_reg", "Crear Cuenta Nueva" },
            { "login_err_auth", "Usuario o contraseña incorrectos." },
               { "login_welcome", "¡Bienvenido, {0}!" },

            { "reg_title", "REGISTRO" },
            { "reg_subtitle", "Crear una nueva cuenta segura" },
            { "reg_lbl_user", "NUEVO USUARIO" },
            { "reg_lbl_pass", "CONTRASEÑA" },
            { "reg_btn_create", "CREAR CUENTA" },
            { "reg_btn_back", "Volver al Login" },
            { "reg_err_len", "Usuario: Min 3 letras.\nPass: Min 4 letras." },
            { "reg_err_exists", "El usuario ya existe." },
            { "reg_msg_code", "¡Cuenta Creada! GUARDA TU CÓDIGO:" },
            { "reg_msg_login", "Registro exitoso!" },
            { "cfg_btn_reset", "⚠️ Eliminar Cuenta" },
            { "btn_exit_user", "Salir ({0})" },


        };
        #endregion

        // =============================================================
        // 2. ENGLISH (EN)
        // =============================================================
        #region DICCIONARIO INGLÉS (EN)
        private static readonly Dictionary<string, string> EN = new Dictionary<string, string>
        {
            { "menu_protect", "🔒  LOCK FOLDER" },
            { "menu_unlock", "🔓  OPEN VAULT" },
            { "menu_files", "📂  MY FILES" },
            { "menu_config", "⚙️ SETTINGS" },
            { "menu_manual", "📘  USER MANUAL" },
            { "menu_exit", "🚪  EXIT" },
            { "title_main", "Security Center" },
            { "app_subtitle", "Security Suite" },
            { "tab_restore", "🔓  RESTORE" },
            { "lbl_target", "TARGET FOLDER (CHOOSE DIRECTORY)" },
            { "lbl_pass", "ENCRYPTION KEY (PASSWORD)" },
            { "link_forgot", "Forgot password?" },
            { "btn_browse", "Browse..." },
            { "btn_lock", "START LOCKING" },
            { "lbl_path_protected", "CURRENT PROTECTED PATH" },
            { "btn_decrypt", "DECRYPT PERMANENTLY" },
            { "title_virtual", "Secure Virtual Access" },
            { "lbl_vaults", "MY VAULTS (SELECT ONE)" },
            { "lbl_drive", "DRIVE LETTER" },
            { "lbl_mount_pass", "ENCRYPTION KEY (PASSWORD)" },
            { "btn_mount", "OPEN VIRTUAL DRIVE" },
            { "btn_unmount", "CLOSE DRIVE" },
            { "setup_title", "WELCOME TO LOCKER" },
            { "setup_sub", "Initial security setup." },
            { "setup_lbl_create", "CREATE MASTER PASSWORD" },
            { "setup_lbl_confirm", "CONFIRM PASSWORD" },
            { "setup_note", "⚠️ Remember your username and password. If you forget them and do not have the recovery code,\nyour files will be irrecoverable." },
            { "setup_btn", "ESTABLISH SECURITY" },
            { "config_title", "SETTINGS" },
            { "config_lbl_lang", "IDIOMA" },
            { "config_chk_start", "Start FolderLocker with Windows (Minimized)" },
            { "cfg_sec_general", "🌍  GENERAL" },
            { "cfg_sec_system", "💻  SYSTEM" },
            { "cfg_sec_data", "🛡️  PRIVACY & DATA" },
            { "cfg_btn_clear", "CLEAR FOLDER HISTORY" },
            { "cfg_msg_clear", "Are you sure? Saved folder locations will be forgotten (files are not deleted)." },
            { "cfg_msg_reset", "⚠️ This will delete your account and settings.\nMake sure you have decrypted your folders before deleting.\nContinue?" },
            { "cfg_done", "Operation successful." },
            { "manual_title", "QUICK USER GUIDE" },
            { "manual_text", "1. PROTECT FOLDER:\n    - Go to the 'Protect' tab.\n    - Choose a folder and enter your password.\n    - The folder will be hidden and encrypted.\n\n2. ACCESS FILES (OPEN VAULT):\n    - Go to 'Open Vault' in the side menu.\n    - Select your folder from the list.\n    - Choose a drive letter (e.g.: M:) and enter your password.\n    - It will open as a secure virtual drive.\n\n3. RESTORE (REMOVE PROTECTION):\n    - Inside the 'Protect' tab there is the 'Restore' option.\n    - Select the folder to restore and enter your password.\n    - The folder will return to normal, it will be decrypted and made visible.\n\n4. ⚠️ CRITICAL WARNINGS (READ):\n    - NEVER enter the hidden folder to paste files manually! They will be damaged when attempting to decrypt them.\n    - Use the virtual drive (Letter:) to edit your files. Alternatively, decrypt the folder, create, move, or edit your new files, and then encrypt it again.\n    - DO NOT delete the 'dir.idx' or 'locker.id' files, or you will lose access to everything.\n    - If you forget your password AND lose your REC code, there is no human way to recover your data.\n    - DO NOT shut down the computer while a large folder is being protected/restored, or data loss may occur." },
            { "msg_select_dir", "Please select a directory." },
            { "msg_pass_wrong", "Incorrect password." },
            { "msg_already_list", "This folder is already in your list." },
            { "msg_rec_title", "Smart Recovery" },
            { "msg_rec_text", "Folder Recovered!\nThis folder was already protected.\nIt has been added to your list without modifying files." },
            { "msg_lock_success", "Folder encrypted and added to the vault." },
            { "msg_select_restore", "Please select a folder." },
            { "msg_confirm_decrypt", "Decrypt folder:\n{0}?" },
            { "msg_decrypt_success", "Folder successfully restored at:" },
            { "msg_mount_select", "Select a folder from the list." },
            { "msg_mount_select_drive", "Select a drive" },
            { "err_not_owner", "⛔ ACCESS DENIED\nThis folder belongs to another user" },
            { "msg_mount_active", "This folder is already open on drive {0}" },
            { "msg_drive_busy", "Drive {0} is busy. Choose another." },
            { "msg_mount_success", "Drive {0} is ACTIVE.\nYou can access it from the 'My Files' menu." },
            { "msg_unmount_select", "Select which folder to close from the list." },
            { "msg_unmount_success", "Drive {0} closed successfully." },
            { "msg_unmount_error", "Problem unmounting. Check for open files." },
            { "msg_no_vault", "No open vaults found. Mount one first." },
            { "err_drag_folder", "Please drag a folder, not a single file." },
            { "err_drag_folder_title", "Folders Only" },
            { "err_root", "⚠️ CRITICAL ERROR ⚠️\nYou are trying to lock a WHOLE DRIVE ({0}).\nThis would corrupt the drive.\n\nSOLUTION: Create a folder inside the drive and select that." },
            { "err_self", "⛔ AUTO-LOCK PREVENTED\nYou cannot lock the folder where this program is running." },
            { "err_sys", "⛔ SYSTEM PROTECTION\nModifying Windows system folders is not allowed." },
            { "err_security_title", "Operation Aborted by Security" },
            { "status_processing", "⏳ PROCESSING..." },
            { "status_decrypting", "⏳ DECRYPTING..." },
            { "tray_working", "Locker - Working" },
            { "tray_working_desc", "Process running in background. Double click here to view progress." },
            { "tray_done", "Locker - Finished" },
            { "tray_done_lock", "Folder locked successfully." },
            { "tray_done_decrypt", "Folder restored successfully." },
            { "tray_minimized_title", "FolderLocker Active" },
            { "tray_minimized_msg", "The application is running in the background." },
            { "tray_menu_open", "Open Locker" },
            { "tray_menu_exit", "Exit" },
            { "btn_accept", "ACCEPT" },
            { "btn_cancel", "CANCEL" },
            { "btn_yes", "YES, CONTINUE" },
            { "btn_ready", "DONE" },
            { "prog_title", "PROCESSING VAULT..." },
            { "prog_init", "Starting..." },
            { "prog_hide_btn", "⬇️ Hide and work in background" },
            { "prog_file_lbl", "Processing: {0}" },
            { "prog_done", "Finishing..." },
            { "status_done", "Done!" },
            { "title_info", "Info" },
            { "title_confirm", "Confirm" },
            { "title_error", "Error" },
            { "title_warning", "Warning" },
            { "title_success", "Success" },
            { "title_security", "Security" },
            { "val_min_chars", "Min: 4 chars." },
            { "val_no_match", "Passwords do not match." },
            { "val_save_code", "SAVE THIS CODE IN A SAFE PLACE:" },
            { "rec_prompt_title", "Account Recovery" },
            { "rec_prompt_msg", "Enter Recovery Code (REC-XXXX):" },
            { "rec_success_msg", "Success! Your password is:" },
            { "rec_fail_msg", "Invalid or incorrect code." },
            // LOGIN & REGISTER
            { "login_title", "LOGIN" },
            { "login_lbl_user", "USERNAME" },
            { "login_lbl_pass", "PASSWORD" },
            { "login_btn_enter", "SIGN IN" },
            { "login_btn_reg", "Create New Account" },
            { "login_err_auth", "Invalid username or password." },
            { "login_welcome", "Welcome, {0}!" },

            { "reg_title", "REGISTER" },
            { "reg_subtitle", "Create a new secure account" },
            { "reg_lbl_user", "NEW USERNAME" },
            { "reg_lbl_pass", "PASSWORD" },
            { "reg_btn_create", "CREATE ACCOUNT" },
            { "reg_btn_back", "Back to Login" },
            { "reg_err_len", "User: Min 3 chars.\nPass: Min 4 chars." },
            { "reg_err_exists", "Username already exists." },
            { "reg_msg_code", "Account Created! SAVE YOUR CODE:" },
            { "reg_msg_login", "Registration successful!" },
            { "login_chk_remember", "Remember Me" },
            { "msg_logout_confirm", "Log out of current session?" },
            { "cfg_btn_reset", "⚠️ Delete Account" },
            { "btn_exit_user", "Exit ({0})" },
            { "str_0", "Very Weak" },
            { "str_1", "Weak" },
            { "str_2", "Average" },
            { "str_3", "Good" },
            { "str_4", "Strong" },
            { "str_5", "Excellent" },
            { "tray_min_title", "FolderLocker Minimized" },
            { "tray_min_click", "Program minimized, click here to open." },
        };
        #endregion

        // =============================================================
        // 3. PORTUGUÊS (PT)
        // =============================================================
        #region DICCIONARIO PORTUGUÉS (PT)
        private static readonly Dictionary<string, string> PT = new Dictionary<string, string>
        {
            { "menu_protect", "🔒  PROTEGER" },
            { "menu_unlock", "🔓  ABRIR COFRE" },
            { "menu_files", "📂  MEUS ARQUIVOS" },
            { "menu_config", "⚙️ CONFIGURAÇÕES" },
            { "menu_manual", "📘  MANUAL" },
            { "menu_exit", "🚪  SAIR" },
            { "title_main", "Centro de Segurança" },
            { "app_subtitle", "Suíte de Segurança" },
            { "tab_restore", "🔓  RESTAURAR" },
            { "lbl_target", "PASTA ALVO (ESCOLHER DIRETÓRIO)" },
            { "lbl_pass", "CHAVE DE CRIPTOGRAFIA (SENHA)" },
            { "link_forgot", "Esqueceu a senha?" },
            { "btn_browse", "Procurar..." },
            { "btn_lock", "INICIAR BLOQUEIO" },
            { "lbl_path_protected", "CAMINHO PROTEGIDO ATUAL" },
            { "btn_decrypt", "DESCRIPTOGRAFAR PERMANENTEMENTE" },
            { "title_virtual", "Acesso Virtual Seguro" },
            { "lbl_vaults", "MEUS COFRES (SELECIONE UM)" },
            { "lbl_drive", "LETRA DA UNIDADE" },
            { "lbl_mount_pass", "CHAVE DE CRIPTOGRAFIA (SENHA)" },
            { "btn_mount", "ABRIR UNIDADE VIRTUAL" },
            { "btn_unmount", "FECHAR UNIDADE" },
            { "setup_title", "BEM-VINDO AO LOCKER" },
            { "setup_sub", "Configuração inicial de segurança." },
            { "setup_lbl_create", "CRIE SUA SENHA MESTRA" },
            { "setup_lbl_confirm", "CONFIRME A SENHA" },
            { "setup_note", "⚠️ Lembre-se do seu nome de usuário e senha. Se você esquecer e não tiver o código de recuperação,\nseus arquivos serão irrecuperáveis." },
            { "setup_btn", "ESTABELECER SEGURANÇA" },
            { "config_title", "CONFIGURAÇÕES" },
            { "config_lbl_lang", "IDIOMA" },
            { "config_chk_start", "Iniciar FolderLocker com Windows (Minimizado)" },
            { "cfg_sec_general", "🌍  GERAL" },
            { "cfg_sec_system", "💻  SISTEMA" },
            { "cfg_sec_data", "🛡️  PRIVACIDADE E DADOS" },
            { "cfg_btn_clear", "LIMPAR HISTÓRICO DE ROTAS" },
            { "cfg_msg_clear", "Tem certeza? As localizações salvas serão esquecidas (arquivos não são apagados)." },
            { "cfg_msg_reset", "⚠️ Isso excluirá sua conta e configurações.\nCertifique-se de ter descriptografado suas pastas antes de excluir.\nContinuar?" },
            { "cfg_done", "Operação realizada com sucesso." },
            { "manual_title", "GUIA RÁPIDO DO USUÁRIO" },
            { "manual_text", "1. PROTEGER PASTA:\n    - Vá para a aba 'Proteger'.\n    - Escolha uma pasta e insira sua senha.\n    - A pasta será oculta e criptografada.\n\n2. ACESSAR ARQUIVOS (ABRIR COFRE):\n    - Vá para 'Abrir Cofre' no menu lateral.\n    - Selecione sua pasta na lista.\n    - Escolha uma letra (ex: M:) e insira sua senha.\n    - Será aberto como um disco virtual seguro.\n\n3. RESTAURAR (REMOVER PROTEÇÃO):\n    - Dentro da aba 'Proteger' está a opção 'Restaurar'.\n    - Selecione a pasta a restaurar e insira sua senha.\n    - A pasta voltará ao normal, será descriptografada e ficará visível.\n\n4. ⚠️ AVISOS CRÍTICOS (LER):\n    - NUNCA entre na pasta oculta para colar arquivos manualmente! Eles serão danificados ao tentar descriptografá-los.\n    - Use a unidade virtual (Letra:) para editar seus arquivos. Ou, em alternativa, descriptografe a pasta, crie, mova ou edite seus novos arquivos e, em seguida, criptografe-a novamente.\n    - NÃO apague os arquivos 'dir.idx' ou 'locker.id', ou você perderá o acesso a tudo.\n    - Se você esquecer sua senha E perder seu código REC, não há como recuperar seus dados.\n    - NÃO DESLIGUE o computador enquanto uma pasta grande estiver sendo protegida/restaurada, pode haver perda de dados." },
            { "msg_select_dir", "Selecione um diretório." },
            { "msg_pass_wrong", "Senha incorreta." },
            { "msg_already_list", "Esta pasta já está na sua lista." },
            { "msg_rec_title", "Recuperação Inteligente" },
            { "msg_rec_text", "Pasta Recuperada!\nEsta pasta já estava protegida.\nFoi adicionada à sua lista sem modificar arquivos." },
            { "msg_lock_success", "Pasta criptografada e adicionada ao cofre." },
            { "msg_select_restore", "Por favor, selecione uma pasta." },
            { "msg_confirm_decrypt", "Descriptografar a pasta:\n{0}?" },
            { "msg_decrypt_success", "Pasta restaurada com sucesso em:" },
            { "msg_mount_select", "Selecione uma pasta da lista." },
            { "msg_mount_select_drive", "Selecione uma unidade" },
            { "err_not_owner", "⛔ ACESSO NEGADO\nEsta pasta pertence a outro usuário" },
            { "msg_mount_active", "Esta pasta já está aberta na unidade {0}" },
            { "msg_drive_busy", "A letra {0} já está em uso. Escolha outra." },
            { "msg_mount_success", "Unidade {0} ATIVA.\nVocê pode acessá-la no menu 'Meus Arquivos'." },
            { "msg_unmount_select", "Selecione na lista qual pasta deseja fechar." },
            { "msg_unmount_success", "Unidade {0} fechada corretamente." },
            { "msg_unmount_error", "Problema ao desmontar. Verifique se há arquivos abertos." },
            { "msg_no_vault", "Nenhum cofre aberto. Monte um primeiro." },
            { "err_drag_folder", "Por favor, arraste uma pasta, não um arquivo." },
            { "err_drag_folder_title", "Apenas Pastas" },
            { "err_root", "⚠️ ERRO CRÍTICO ⚠️\nVocê está tentando bloquear um DISCO INTEIRO ({0}).\nIsso corromperia a unidade.\nSOLUÇÃO: Crie uma pasta dentro do disco e selecione-a." },
            { "err_self", "⛔ AUTO-BLOQUEIO PREVENIDO\nVocê não pode bloquear a pasta onde este programa está rodando." },
            { "err_sys", "⛔ PROTEÇÃO DE SISTEMA\nNão é permitido modificar pastas do Windows." },
            { "err_security_title", "Operação Abortada por Segurança" },
            { "status_processing", "⏳ PROCESSANDO..." },
            { "status_decrypting", "⏳ DESCRIPTOGRAFANDO..." },
            { "tray_working", "Locker - Trabalhando" },
            { "tray_working_desc", "O processo continua em segundo plano. Clique duas vezes para ver." },
            { "tray_done", "Locker - Finalizado" },
            { "tray_done_lock", "A pasta foi bloqueada com sucesso." },
            { "tray_done_decrypt", "Pasta restaurada corretamente." },
            { "tray_minimized_title", "FolderLocker Ativo" },
            { "tray_minimized_msg", "O aplicativo continua rodando em segundo plano." },
            { "tray_menu_open", "Abrir Locker" },
            { "tray_menu_exit", "Sair" },
            { "btn_accept", "ACEITAR" },
            { "btn_cancel", "CANCELAR" },
            { "btn_yes", "SIM, CONTINUAR" },
            { "btn_ready", "PRONTO" },
            { "prog_title", "PROCESSANDO COFRE..." },
            { "prog_init", "Iniciando..." },
            { "prog_hide_btn", "⬇️ Ocultar e trabalhar em 2º plano" },
            { "prog_file_lbl", "Processando: {0}" },
            { "prog_done", "Finalizando..." },
            { "status_done", "Feito!" },
            { "title_info", "Informação" },
            { "title_confirm", "Confirmar" },
            { "title_error", "Erro" },
            { "title_warning", "Aviso" },
            { "title_success", "Sucesso" },
            { "title_security", "Segurança" },
            { "val_min_chars", "Mínimo 4 caracteres." },
            { "val_no_match", "As senhas não coincidem." },
            { "val_save_code", "GUARDE ESTE CÓDIGO EM UM LUGAR SEGURO:" },
            { "rec_prompt_title", "Recuperação de Conta" },
            { "rec_prompt_msg", "Digite seu Código de Recuperação (REC-XXXX):" },
            { "rec_success_msg", "Sucesso! Sua senha é:" },
            { "rec_fail_msg", "Código incorreto ou inválido." },
            // LOGIN & REGISTRO
            { "login_title", "ENTRAR" },
            { "login_lbl_user", "USUÁRIO" },
            { "login_lbl_pass", "SENHA" },
            { "login_btn_enter", "ENTRAR" },
            { "login_btn_reg", "Criar Nova Conta" },
            { "login_err_auth", "Usuário ou senha incorretos." },
            { "login_welcome", "Bem-vindo, {0}!" },

            { "reg_title", "REGISTRO" },
            { "reg_subtitle", "Criar uma nova conta segura" },
            { "reg_lbl_user", "NOVO USUÁRIO" },
            { "reg_lbl_pass", "SENHA" },
            { "reg_btn_create", "CRIAR CONTA" },
            { "reg_btn_back", "Voltar para Login" },
            { "reg_err_len", "Usuário: Min 3 letras.\nSenha: Min 4 letras." },
            { "reg_err_exists", "O usuário já existe." },
            { "reg_msg_code", "Conta Criada! GUARDE SEU CÓDIGO:" },
            { "reg_msg_login", "Registro bem-sucedido!" },
            { "login_chk_remember", "Lembrar Usuário" },
            { "msg_logout_confirm", "Sair da sessão atual?" },
            { "cfg_btn_reset", "⚠️ Excluir Conta" },
            { "btn_exit_user", "Sair ({0})" },
            { "str_0", "Muito Fraco" },
            { "str_1", "Fraco" },
            { "str_2", "Normal" },
            { "str_3", "Bom" },
            { "str_4", "Forte" },
            { "str_5", "Excelente" },
            { "tray_min_title", "FolderLocker Minimizado" },
            { "tray_min_click", "Programa minimizado, clique aqui para abrir." },
        };
        #endregion

        // =============================================================
        // 4. RUSO (RU)
        // =============================================================
        #region DICCIONARIO RUSO (RU)
        private static readonly Dictionary<string, string> RU = new Dictionary<string, string>
        {
            { "menu_protect", "🔒  ЗАЩИТИТЬ" },
            { "menu_unlock", "🔓  ОТКРЫТЬ СЕЙФ" },
            { "menu_files", "📂  МОИ ФАЙЛЫ" },
            { "menu_config", "⚙️ НАСТРОЙКИ" },
            { "menu_manual", "📘  РУКОВОДСТВО" },
            { "menu_exit", "🚪  ВЫХОД" },
            { "title_main", "Центр Безопасности" },
            { "app_subtitle", "Пакет Безопасности" },
            { "tab_restore", "🔓  ВОССТАНОВИТЬ" },
            { "lbl_target", "ЦЕЛЕВАЯ ПАПКА (ВЫБРАТЬ)" },
            { "lbl_pass", "КЛЮЧ ШИФРОВАНИЯ (ПАРОЛЬ)" },
            { "link_forgot", "Забыли пароль?" },
            { "btn_browse", "Обзор..." },
            { "btn_lock", "НАЧАТЬ БЛОКИРОВКУ" },
            { "lbl_path_protected", "ТЕКУЩИЙ ЗАЩИЩЕННЫЙ ПУТЬ" },
            { "btn_decrypt", "РАСШИФРОВАТЬ НАВСЕГДА" },
            { "title_virtual", "Безопасный Виртуальный Доступ" },
            { "lbl_vaults", "МОИ СЕЙФЫ (ВЫБЕРИТЕ ОДИН)" },
            { "lbl_drive", "БУКВА ДИСКА" },
            { "lbl_mount_pass", "КЛЮЧ ШИФРОВАНИЯ (ПАРОЛЬ)" },
            { "btn_mount", "ОТКРЫТЬ ВИРТУАЛЬНЫЙ ДИСК" },
            { "btn_unmount", "ЗАКРЫТЬ ДИСК" },
            { "setup_title", "ДОБРО ПОЖАЛОВАТЬ В LOCKER" },
            { "setup_sub", "Начальная настройка безопасности." },
            { "setup_lbl_create", "СОЗДАЙТЕ МАСТЕР-ПАРОЛЬ" },
            { "setup_lbl_confirm", "ПОДТВЕРДИТЕ ПАРОЛЬ" },
            { "setup_note", "⚠️ Запомните ваше имя пользователя и пароль. Если вы их забудете и не имеете код восстановления,\nваши файлы станут невосстановимыми." },
            { "setup_btn", "УСТАНОВИТЬ ЗАЩИТУ" },
            { "config_title", "НАСТРОЙКИ" },
            { "config_lbl_lang", "IDIOMA" },
            { "config_chk_start", "Запускать с Windows (свернуто)" },
            { "cfg_sec_general", "🌍  ОБЩИЕ" },
            { "cfg_sec_system", "💻  СИСТЕМА" },
            { "cfg_sec_data", "🛡️  КОНФИДЕНЦИАЛЬНОСТЬ" },
            { "cfg_btn_clear", "ОЧИСТИТЬ ИСТОРИЮ" },
            { "cfg_msg_clear", "Вы уверены? Сохраненные пути будут забыты (файлы не удаляются)." },
            { "cfg_msg_reset", "⚠️ Это удалит вашу учетную запись и настройки.\nУбедитесь, что вы расшифровали папки перед удалением.\nПродолжить?" },
            { "cfg_done", "Операция выполнена успешно." },
            { "manual_title", "КРАТКОЕ РУКОВОДСТВО" },
            { "manual_text", "1. ЗАЩИТИТЬ ПАПКУ:\n    - Перейдите на вкладку 'Защитить'.\n    - Выберите папку и введите пароль.\n    - Папка будет скрыта и зашифрована.\n\n2. ДОСТУП К ФАЙЛАМ (ОТКРЫТЬ ХРАНИЛИЩЕ):\n    - Перейдите в 'Открыть Хранилище' в боковом меню.\n    - Выберите папку из списка.\n    - Выберите букву (напр.: M:) и введите пароль.\n    - Она откроется как безопасный виртуальный диск.\n\n3. ВОССТАНОВИТЬ (СНЯТЬ ЗАЩИТУ):\n    - На вкладке 'Защитить' есть опция 'Восстановить'.\n    - Выберите папку для восстановления и введите пароль.\n    - Папка вернется в обычное состояние, будет расшифрована и станет видимой.\n\n4. ⚠️ КРИТИЧЕСКИЕ ПРЕДУПРЕЖДЕНИЯ (ПРОЧИТАТЬ):\n    - НИКОГДА не заходите в скрытую папку для ручной вставки файлов! Они будут повреждены при попытке расшифровки.\n    - Используйте виртуальный диск (Буква: ) для редактирования файлов. Либо расшифруйте папку, создайте, переместите или отредактируйте новые файлы, а затем снова зашифруйте.\n    - НЕ удаляйте файлы 'dir.idx' или 'locker.id', иначе вы потеряете доступ ко всему.\n    - Если вы забудете свой пароль И потеряете код REC, восстановить данные невозможно.\n    - НЕ ВЫКЛЮЧАЙТЕ компьютер во время защиты/восстановления большой папки, это может привести к потере данных." },
            { "msg_select_dir", "Пожалуйста, выберите директорию." },
            { "msg_pass_wrong", "Неверный пароль." },
            { "msg_already_list", "Эта папка уже в вашем списке." },
            { "msg_rec_title", "Умное Восстановление" },
            { "msg_rec_text", "Папка восстановлена!\nЭта папка уже была защищена.\nОна добавлена в список без изменений файлов." },
            { "msg_lock_success", "Папка зашифрована и добавлена в сейф." },
            { "msg_select_restore", "Пожалуйста, выберите папку." },
            { "msg_confirm_decrypt", "Расшифровать папку:\n{0}?" },
            { "msg_decrypt_success", "Папка успешно восстановлена в:" },
            { "msg_mount_select", "Выберите папку из списка." },
            { "msg_mount_select_drive", "Выберите диск" },
            { "err_not_owner", "⛔ ДОСТУП ЗАПРЕЩЕН\nЭта папка принадлежит другому пользователю" },
            { "msg_mount_active", "Эта папка уже открыта на диске {0}" },
            { "msg_drive_busy", "Диск {0} занят. Выберите другой." },
            { "msg_mount_success", "Диск {0} АКТИВЕН.\nВы можете получить доступ через меню 'Мои файлы'." },
            { "msg_unmount_select", "Выберите папку для закрытия." },
            { "msg_unmount_success", "Диск {0} успешно закрыт." },
            { "msg_unmount_error", "Ошибка закрытия. Проверьте открытые файлы." },
            { "msg_no_vault", "Нет открытых сейфов. Сначала подключите один." },
            { "err_drag_folder", "Пожалуйста, перетащите папку, а не файл." },
            { "err_drag_folder_title", "Только Папки" },
            { "err_root", "⚠️ КРИТИЧЕСКАЯ ОШИБКА ⚠️\nВы пытаетесь заблокировать ВЕСЬ ДИСК ({0}).\nЭто повредит данные.\nРЕШЕНИЕ: Создайте папку на диске и выберите её." },
            { "err_self", "⛔ БЛОКИРОВКА ПРЕДОТВРАЩЕНА\nНельзя блокировать папку, где запущена программа." },
            { "err_sys", "⛔ ЗАЩИТА СИСТЕМЫ\nМодификация системных папок Windows запрещена." },
            { "err_security_title", "Операция Прервана" },
            { "status_processing", "⏳ ОБРАБОТКА..." },
            { "status_decrypting", "⏳ РАСШИФРОВКА..." },
            { "tray_working", "Locker - Работает" },
            { "tray_working_desc", "Процесс идет в фоне. Дважды кликните для просмотра." },
            { "tray_done", "Locker - Готово" },
            { "tray_done_lock", "Папка успешно заблокирована." },
            { "tray_done_decrypt", "Папка успешно восстановлена." },
            { "tray_minimized_title", "FolderLocker Активен" },
            { "tray_minimized_msg", "Приложение работает в фоновом режиме." },
            { "tray_menu_open", "Открыть Locker" },
            { "tray_menu_exit", "Выход" },
            { "btn_accept", "ПРИНЯТЬ" },
            { "btn_cancel", "ОТМЕНА" },
            { "btn_yes", "ДА, ПРОДОЛЖИТЬ" },
            { "btn_ready", "ГОТОВО" },
            { "prog_title", "ОБРАБОТКА СЕЙФА..." },
            { "prog_init", "Запуск..." },
            { "prog_hide_btn", "⬇️ Скрыть и работать в фоне" },
            { "prog_file_lbl", "Обработка: {0}" },
            { "prog_done", "Завершение..." },
            { "status_done", "Готово!" },
            { "title_info", "Информация" },
            { "title_confirm", "Подтверждение" },
            { "title_error", "Ошибка" },
            { "title_warning", "Внимание" },
            { "title_success", "Успех" },
            { "title_security", "Безопасность" },
            { "val_min_chars", "Минимум 4 символа." },
            { "val_no_match", "Пароли не совпадают." },
            { "val_save_code", "СОХРАНИТЕ ЭТОТ КОД В БЕЗОПАСНОМ МЕСТЕ:" },
            { "rec_prompt_title", "Восстановление Аккаунта" },
            { "rec_prompt_msg", "Введите Код Восстановления (REC-XXXX):" },
            { "rec_success_msg", "Успех! Ваш пароль:" },
            { "rec_fail_msg", "Неверный или некорректный код." },
            // LOGIN & REGISTER
            { "login_title", "ВХОД" },
            { "login_lbl_user", "ПОЛЬЗОВАТЕЛЬ" },
            { "login_lbl_pass", "ПАРОЛЬ" },
            { "login_btn_enter", "ВОЙТИ" },
            { "login_btn_reg", "Создать новую учетную запись" },
            { "login_err_auth", "Неверное имя пользователя или пароль." },
            { "login_welcome", "Добро пожаловать, {0}!" },

            { "reg_title", "РЕГИСТРАЦИЯ" },
            { "reg_subtitle", "Создать безопасный аккаунт" },
            { "reg_lbl_user", "НОВЫЙ ПОЛЬЗОВАТЕЛЬ" },
            { "reg_lbl_pass", "ПАРОЛЬ" },
            { "reg_btn_create", "СОЗДАТЬ АККАУНТ" },
            { "reg_btn_back", "Назад ко входу" },
            { "reg_err_len", "Логин: Мин 3 симв.\nПароль: Мин 4 симв." },
            { "reg_err_exists", "Пользователь уже существует." },
            { "reg_msg_code", "Аккаунт создан! СОХРАНИТЕ КОД:" },
            { "reg_msg_login", "Регистрация прошла успешно!" },
            { "login_chk_remember", "Запомнить меня" },
            { "msg_logout_confirm", "Выйти из системы?" },
            { "cfg_btn_reset", "⚠️ Excluir Conta" },
            { "btn_exit_user", "Выход ({0})" },
            { "str_0", "Очень слабый" },
            { "str_1", "Слабый" },
            { "str_2", "Нормальный" },
            { "str_3", "Хороший" },
            { "str_4", "Сильный" },
            { "str_5", "Отличный" },
            { "tray_min_title", "FolderLocker Свернут" },
            { "tray_min_click", "Программа свернута, нажмите здесь, чтобы открыть." },


        };
        #endregion

        // =============================================================
        // 5. CHINO MANDARÍN (ZH)
        // =============================================================
        #region DICCIONARIO CHINO (CN)
        private static readonly Dictionary<string, string> CN = new Dictionary<string, string>
        {
            { "menu_protect", "🔒  保护文件夹" },
            { "menu_unlock", "🔓  打开保险库" },
            { "menu_files", "📂  我的文件" },
            { "menu_config", "⚙️ 设置" },
            { "menu_manual", "📘  用户手册" },
            { "menu_exit", "🚪  退出" },
            { "title_main", "安全中心" },
            { "app_subtitle", "安全套件" },
            { "tab_restore", "🔓  恢复" },
            { "lbl_target", "目标文件夹（选择目录）" },
            { "lbl_pass", "加密密钥（密码）" },
            { "link_forgot", "忘记密码？" },
            { "btn_browse", "浏览..." },
            { "btn_lock", "开始锁定" },
            { "lbl_path_protected", "当前受保护路径" },
            { "btn_decrypt", "永久解密" },
            { "title_virtual", "安全虚拟访问" },
            { "lbl_vaults", "我的保险库（选择一个）" },
            { "lbl_drive", "驱动器号" },
            { "lbl_mount_pass", "加密密钥（密码）" },
            { "btn_mount", "打开虚拟驱动器" },
            { "btn_unmount", "关闭驱动器" },
            { "setup_title", "欢迎使用 文件夹锁" },
            { "setup_sub", "初始安全设置。" },
            { "setup_lbl_create", "创建主密码" },
            { "setup_lbl_confirm", "确认密码" },
            { "setup_note", "⚠️ 请记住您的用户名和密码。如果您忘记了且没有恢复代码,\n您的文件将无法恢复。" },
            { "setup_btn", "建立安全" },
            { "config_title", "设置" },
            { "config_lbl_lang", "语言" },
            { "config_chk_start", "随 Windows 启动（最小化）" },
            { "cfg_sec_general", "🌍  常规" },
            { "cfg_sec_system", "💻  系统" },
            { "cfg_sec_data", "🛡️  隐私与数据" },
            { "cfg_btn_clear", "清除路径历史" },
            { "cfg_msg_clear", "确定吗？保存的文件夹位置将被遗忘（文件不会被删除）。" },
            { "cfg_msg_reset", "⚠️ 这将删除您的账户和配置。\n请确保在删除前已解密您的文件夹。\n是否继续?" },
            { "cfg_done", "操作成功完成。" },
            { "manual_title", "快速用户指南" },
            { "manual_text", "1. 保护文件夹:\n    - 转到“保护”选项卡。\n    - 选择一个文件夹并输入您的密码。\n    - 该文件夹将被隐藏和加密。\n\n2. 访问文件 (打开保险库):\n    - 转到侧边菜单中的“打开保险库”。\n    - 从列表中选择您的文件夹。\n    - 选择一个盘符 (例如：M:) 并输入您的密码。\n    - 它将以安全虚拟驱动器的形式打开。\n\n3. 恢复 (移除保护):\n    - “保护”选项卡内有“恢复”选项。\n    - 选择要恢复的文件夹并输入您的密码。\n    - 该文件夹将恢复正常，它将被解密并可见。\n\n4. ⚠️ 关键警告 (必读):\n    - 切勿手动进入隐藏文件夹粘贴文件！否则在尝试解密时会被损坏。\n    - 使用虚拟驱动器（盘符：）编辑您的文件。 或者，解密文件夹，创建、移动或编辑新文件，然后重新加密。\n    - 请勿删除 'dir.idx' 或 'locker.id' 文件，否则您将失去所有访问权限。\n    - 如果您忘记了密码并且丢失了恢复代码 (REC)，则无法恢复您的数据。\n    - 在保护/恢复大文件夹期间，请勿关闭计算机，否则可能导致数据丢失。" },
            { "msg_select_dir", "请选择一个目录。" },
            { "msg_pass_wrong", "密码错误。" },
            { "msg_already_list", "此文件夹已在您的列表中。" },
            { "msg_rec_title", "智能恢复" },
            { "msg_rec_text", "文件夹已恢复！\n此文件夹已受保护。\n已添加到您的列表，未修改文件。" },
            { "msg_lock_success", "文件夹已加密并添加到保险库。" },
            { "msg_select_restore", "请选择一个文件夹。" },
            { "msg_confirm_decrypt", "解密文件夹：\n{0}？" },
            { "msg_decrypt_success", "文件夹成功恢复至：" },
            { "msg_mount_select", "从列表中选择一个文件夹。" },
            { "msg_mount_select_drive", "选择驱动器" },
            { "err_not_owner", "⛔ 访问被拒绝\n此文件夹属于其他用户" },
            { "msg_mount_active", "此文件夹已在驱动器 {0} 上打开" },
            { "msg_drive_busy", "驱动器 {0} 忙。请选择另一个。" },
            { "msg_mount_success", "驱动器 {0} 已激活。\n您可以通过“我的文件”菜单访问。" },
            { "msg_unmount_select", "在列表中选择要关闭的文件夹。" },
            { "msg_unmount_success", "驱动器 {0} 已成功关闭。" },
            { "msg_unmount_error", "卸载时出错。请检查是否有打开的文件。" },
            { "msg_no_vault", "未找到打开的保险库。请先挂载一个。" },
            { "err_drag_folder", "请拖动文件夹，而不是单个文件。" },
            { "err_drag_folder_title", "仅限文件夹" },
            { "err_root", "⚠️ 严重错误 ⚠️\n您试图锁定整个驱动器 ({0})。\n这会损坏驱动器。\n解决方案：在驱动器内创建一个文件夹并选择它。" },
            { "err_self", "⛔ 自动锁定已阻止\n您无法锁定此程序正在运行的文件夹。" },
            { "err_sys", "⛔ 系统保护\n不允许修改 Windows 系统文件夹。" },
            { "err_security_title", "操作因安全原因中止" },
            { "status_processing", "⏳ 处理中..." },
            { "status_decrypting", "⏳ 解密中..." },
            { "tray_working", "Locker - 正在工作" },
            { "tray_working_desc", "进程在后台运行。双击此处查看进度。" },
            { "tray_done", "Locker - 完成" },
            { "tray_done_lock", "文件夹已成功锁定。" },
            { "tray_done_decrypt", "文件夹已成功恢复。" },
            { "tray_minimized_title", "FolderLocker 活动" },
            { "tray_minimized_msg", "应用程序正在后台运行。" },
            { "tray_menu_open", "打开 Locker" },
            { "tray_menu_exit", "退出" },
            { "btn_accept", "接受" },
            { "btn_cancel", "取消" },
            { "btn_yes", "是，继续" },
            { "btn_ready", "完成" },
            { "prog_title", "正在处理保险库..." },
            { "prog_init", "正在启动..." },
            { "prog_hide_btn", "⬇️ 隐藏并在后台工作" },
            { "prog_file_lbl", "正在处理：{0}" },
            { "prog_done", "正在完成..." },
            { "status_done", "完成！" },
            { "title_info", "信息" },
            { "title_confirm", "确认" },
            { "title_error", "错误" },
            { "title_warning", "警告" },
            { "title_success", "成功" },
            { "title_security", "安全" },
            { "val_min_chars", "最少 4 个字符。" },
            { "val_no_match", "密码不匹配。" },
            { "val_save_code", "请将此代码保存在安全的地方：" },
            { "rec_prompt_title", "账户恢复" },
            { "rec_prompt_msg", "输入恢复代码 (REC-XXXX)：" },
            { "rec_success_msg", "成功！您的密码是：" },
            { "rec_fail_msg", "代码无效或不正确。" },
            // LOGIN & REGISTER
            { "login_title", "登录" },
            { "login_lbl_user", "用户名" },
            { "login_lbl_pass", "密码" },
            { "login_btn_enter", "登录" },
            { "login_btn_reg", "创建新账户" },
            { "login_err_auth", "用户名或密码错误。" },
            { "login_welcome", "欢迎，{0}！" },

            { "reg_title", "注册" },
            { "reg_subtitle", "创建一个新的安全账户" },
            { "reg_lbl_user", "新用户名" },
            { "reg_lbl_pass", "密码" },
            { "reg_btn_create", "创建账户" },
            { "reg_btn_back", "返回登录" },
            { "reg_err_len", "用户：最少3个字符。\n密码：最少4个字符。" },
            { "reg_err_exists", "用户名已存在。" },
            { "reg_msg_code", "账户已创建！保存您的代码：" },
            { "reg_msg_login", "注册成功!" },
            { "login_chk_remember", "记住用户" },
            { "msg_logout_confirm", "退出当前会话？" },
            { "cfg_btn_reset", "⚠️ 删除账户" },
            { "btn_exit_user", "退出 ({0})" },
            { "str_0", "非常弱" },
            { "str_1", "弱" },
            { "str_2", "中等" },
            { "str_3", "好" },
            { "str_4", "强" },
            { "str_5", "优秀" },
            { "tray_min_title", "FolderLocker 已最小化" },
            { "tray_min_click", "程序已最小化，点击此处打开。" },

        };
        #endregion

        // Método inteligente que selecciona el diccionario correcto
        public static string Get(string key)
        {
            Dictionary<string, string> dict;

            switch (CurrentLang)
            {
                case "CN": dict = CN; break;
                case "PT": dict = PT; break;
                case "RU": dict = RU; break;
                case "EN": dict = EN; break;
                default: dict = ES; break;
            }

            return dict.ContainsKey(key) ? dict[key] : key;
        }
    }
}