namespace FolderLocker
{
    public static class Localization
    {
        // Variable global de idioma
        public static string CurrentLang = "ES";

        // =============================================================
        // 1. ESPAÑOL (ES)
        // =============================================================
        #region DICCIONARIO ESPAÑOL (ES)
        private static readonly Dictionary<string, string> ES = new Dictionary<string, string>
        {
            // MENÚ LATERAL
            { "menu_protect", "🔒  PROTEGER" },
            { "menu_unlock", "🔓  ABRIR BÓVEDA" },
            { "menu_files", "📂  MIS ARCHIVOS" },
            { "menu_config", "⚙️ CONFIGURACIÓN" },
            { "menu_manual", "📘  MANUAL DE USO" },
            { "menu_exit", "🚪  SALIR" },

            // HEADER & TABS
            { "title_main", "Centro de Seguridad" },
            { "app_subtitle", "Suite de Seguridad" },
            { "tab_restore", "🔓  RESTAURAR" },

            // PANEL PROTEGER (LOCK)
            { "lbl_target", "CARPETA OBJETIVO (DIRECTORIO A ESCOGER)" },
            { "lbl_pass", "CLAVE DE CIFRADO (CONTRASEÑA)" },
            { "link_forgot", "¿Olvidaste la clave?" },
            { "btn_browse", "Examinar..." },
            { "btn_lock", "INICIAR BLOQUEO" },


            // PANEL RESTAURAR
            { "lbl_path_protected", "RUTA PROTEGIDA ACTUAL" },
            { "btn_decrypt", "DESENCRIPTAR PERMANENTEMENTE" },

            // PANEL MONTAR (VIRTUAL)
            { "title_virtual", "Acceso Virtual Seguro" },
            { "lbl_vaults", "MIS BÓVEDAS (SELECCIONA UNA)" },
            { "placeholder_search_vault", "Buscar bóveda por nombre o ruta..." },
            { "lbl_no_vaults_found", "No se encontraron bóvedas que coincidan con la búsqueda." },
            { "lbl_no_vaults_available", "No tienes ninguna bóveda protegida aún." },
            { "lbl_drive", "LETRA DE UNIDAD" },
            { "lbl_mount_pass", "CLAVE DE CIFRADO (CONTRASEÑA)" },
            { "btn_mount", "ABRIR UNIDAD VIRTUAL" },
            { "btn_unmount", "CERRAR UNIDAD" },

            // PANEL SETUP (BIENVENIDA)
            { "setup_title", "BIENVENIDO A LOCKER" },
            { "setup_sub", "Configuración inicial de seguridad." },
            { "setup_lbl_create", "CREA TU CONTRASEÑA MAESTRA" },
            { "setup_lbl_confirm", "CONFIRMA LA CONTRASEÑA" },
            { "setup_note", "⚠️ Recuerda tu usuario y contraseña, Si te llegas a olvidar y sin el código de recuperación,\ntus archivos serán irrecuperables." },
            { "setup_btn", "ESTABLECER SEGURIDAD" },

            // PANEL CONFIGURACIÓN
            { "config_title", "CONFIGURACIÓN" },
            { "config_lbl_lang", "IDIOMA " },
            { "config_chk_start", "Iniciar FolderLocker con Windows (Minimizado)" },
            { "cfg_sec_general", "🌍  GENERAL" },
            { "cfg_sec_system", "💻  SISTEMA" },
            { "cfg_autolock_title", "Auto-Bloqueo por Inactividad" },
            { "cfg_autolock_sub", "Bloquear sesión y cerrar unidades tras tiempo inactivo." },
            { "msg_autolock_triggered", "🔒 Sesión bloqueada automáticamente por inactividad." },
            { "cfg_sec_data", "🛡️  PRIVACIDAD Y DATOS" },
            { "cfg_btn_clear", "BORRAR HISTORIAL DE RUTAS" },
            { "cfg_msg_clear", "¿Estás seguro? Se olvidarán las ubicaciones de tus carpetas (no se borran los archivos)." },
            { "cfg_msg_reset", "⚠️ Esto borrará tu cuenta y configuración.\nAsegúrate de haber desencriptado tus carpetas antes de eliminar.\n¿Continuar?" },
            { "cfg_done", "Operación realizada con éxito." },
            { "login_chk_remember", "Recordar Usuario" },
            { "msg_logout_confirm", "¿Cerrar la sesión actual?" },

            // MANUAL
            { "manual_title", "GUÍA RÁPIDA DE USUARIO" },
            { "manual_text", "1. PROTEGER CARPETA:\n   - Ve a la pestaña 'Proteger'.\n   - Elige una carpeta y pon tu contraseña.\n   - La carpeta se ocultará y encriptará.\n\n" +
                             "2. ACCEDER A LOS ARCHIVOS (ABRIR BÓVEDA):\n   - Ve a 'Abrir Bóveda' en el menú lateral.\n   - Selecciona tu carpeta de la lista.\n   - Elige una letra (ej: M:) y pon tu contraseña.\n   - Se abrirá como un disco virtual seguro.\n\n" +
                             "3. RESTAURAR (QUITAR PROTECCIÓN):\n   - Dentro de la pestaña 'Proteger' Esta la opcion de 'Restaurar'.\n   - Selecciona la carpeta a restaurar y pon tu contraseña.\n   - La carpeta volverá a ser normal, la desencriptará y la hará visible.\n\n" +
                             "4. ⚠️ ADVERTENCIAS CRÍTICAS (LEER):\n   - ¡NUNCA entres a la carpeta oculta para pegar archivos manualmente! Se dañarán al intentar desencriptarlos.\n   " +
                                "- Usa la unidad virtual (Letra:) para editar tus archivos. o en cambio desencripta la carpeta, crea, pasa o edita tus nuevos archivos y vuelve a encriptar\n   - NO borres los archivos 'dir.idx' ni 'locker.id', o perderás el acceso a todo.\n   " +
                                "- Si olvidas tu contraseña Y pierdes tu código REC, no hay forma humana de recuperar tus datos.\n   " +
                                "- NO APAGUE el equipo mientras se está protegiendo/restaurando una carpeta grande, podría haber pérdida de datos." },

            // MENSAJES Y ERRORES
            { "msg_select_dir", "Selecciona un directorio a escoger." },
            { "msg_pass_wrong", "Contraseña incorrecta." },
            { "msg_already_list", "Esta carpeta ya está en tu lista." },
            { "msg_rec_title", "Recuperación Inteligente" },
            { "msg_rec_text", "¡Carpeta Recuperada!\nEsta carpeta ya estaba protegida anteriormente.\nSe ha añadido a tu lista sin modificar los archivos." },
            { "msg_lock_success", "Carpeta encriptada y agregada a la bóveda." },
            { "msg_select_restore", "Por favor, selecciona una carpeta." },
            { "msg_confirm_decrypt", "¿Estás seguro de Desencriptar la carpeta\n{0}?" },
            { "msg_decrypt_success", "Carpeta Restaurada exitosamente en:" },
            { "msg_mount_select", "Selecciona la carpeta de la lista." },
            { "msg_mount_active", "Esta carpeta ya está abierta en la unidad {0}" },
            { "msg_drive_busy", "La letra {0} ya está en uso. Elige otra." },
            { "msg_mount_success", "Unidad {0} ACTIVA.\nPuedes acceder desde el menu 'Mis Archivos'." },
            { "msg_unmount_select", "Selecciona en la lista qué carpeta quieres cerrar." },
            { "msg_unmount_success", "Unidad {0} cerrada correctamente." },
            { "msg_unmount_error", "Hubo un problema al intentar desmontar. Verifica que no tengas archivos abiertos." },
            { "msg_no_vault", "No hay ninguna bóveda abierta. Monta una primero." },
            { "err_drag_folder", "Por favor, arrastra una carpeta, no un archivo suelto." },
            { "err_drag_folder_title", "Solo Carpetas" },
            { "msg_mount_select_drive","Selecciona una unidad"},
            { "err_not_owner","⛔ ACCESO DENEGADO\nEsta carpeta pertenece a otro usuario."},
            { "str_0", "Muy Débil" },
            { "str_1", "Débil" },
            { "str_2", "Normal" },
            { "str_3", "Buena" },
            { "str_4", "Fuerte" },
            { "str_5", "Excelente" },
            { "tray_min_title", "FolderLocker Minimizado" },
            { "tray_min_click", "Programa minimizado, click aquí para abrir el programa." },


            // SEGURIDAD CRÍTICA
            { "err_root", "⚠️ ERROR CRÍTICO ⚠️\nEstás intentando bloquear un DISCO ENTERO ({0}).\nEsto corrompería la unidad.\n\nSOLUCIÓN: Crea una carpeta dentro del disco y selecciona esa carpeta." },
            { "err_self", "⛔ AUTO-BLOQUEO EVITADO\nNo puedes bloquear la carpeta donde está instalado el programa." },
            { "err_sys", "⛔ PROTECCIÓN DE SISTEMA\nNo se permite modificar carpetas de Windows." },
            { "err_security_title", "Operación Abortada por Seguridad" },

            // PROGRESO Y TRAY
            { "status_processing", "⏳ PROCESANDO..." },
            { "status_decrypting", "⏳ DESENCRIPTANDO..." },
            { "tray_working", "Locker - Trabajando" },
            { "tray_working_desc", "El proceso continúa en segundo plano. Haz doble clic aquí para ver el progreso." },
            { "tray_done", "Locker - Finalizado" },
            { "tray_done_lock", "La carpeta se ha bloqueado exitosamente." },
            { "tray_done_decrypt", "Carpeta restaurada correctamente." },
            { "tray_minimized_title", "FolderLocker Activo" },
            { "tray_minimized_msg", "La aplicación sigue ejecutándose en segundo plano." },
            { "tray_menu_open", "Abrir Locker" },
            { "tray_menu_exit", "Salir" },

            // UI GENERAL
            { "btn_accept", "ACEPTAR" },
            { "btn_cancel", "CANCELAR" },
            { "btn_yes", "SÍ, CONTINUAR" },
            { "btn_ready", "LISTO" },
            { "prog_title", "PROCESANDO BÓVEDA..." },
            { "prog_init", "Iniciando..." },
            { "prog_hide_btn", "👁️ SEGUNDO PLANO" },
            { "prog_pause", "⏸️  PAUSAR" },
            { "prog_resume", "▶️  REANUDAR" },
            { "prog_cancel", "🛑  CANCELAR" },
            { "prog_paused", "⏸️ Operación en pausa por el usuario" },
            { "prog_confirm_cancel", "¿Deseas cancelar la operación en curso?\n\nLos archivos procesados hasta ahora se mantendrán protegidos." },
            { "msg_op_cancelled", "La operación fue cancelada por el usuario. Los archivos pendientes no fueron modificados." },
            { "prog_file_lbl", "Procesando: {0}" },
            { "prog_done", "Finalizando..." },
            { "status_done", "¡Hecho!" },

            // VALIDACIONES Y RECUPERACIÓN
            { "title_info", "Información" },
            { "title_confirm", "Confirmar" },
            { "title_error", "Error" },
            { "title_warning", "Advertencia" },
            { "title_success", "Éxito" },
            { "title_security", "Seguridad" },
            { "val_min_chars", "Mínimo 4 caracteres." },
            { "val_no_match", "Las contraseñas no coinciden." },
            { "val_save_code", "GUARDA ESTE CÓDIGO EN UN LUGAR SEGURO:" },
            { "rec_prompt_title", "Recuperación de Cuenta" },
            { "rec_prompt_msg", "Ingrese su Código de Recuperación (REC-XXXX):" },
            { "rec_success_msg", "¡Éxito! Tu contraseña es:" },
            { "rec_fail_msg", "Código incorrecto o inválido." },

            // LOGIN & REGISTRO
            { "login_title", "INICIAR SESIÓN" },
            { "login_lbl_user", "USUARIO" },
            { "login_lbl_pass", "CONTRASEÑA" },
            { "login_btn_enter", "ENTRAR" },
            { "login_btn_reg", "Crear Cuenta Nueva" },
            { "login_err_auth", "Usuario o contraseña incorrectos." },
               { "login_welcome", "¡Bienvenido, {0}!" },

            { "reg_title", "REGISTRO" },
            { "reg_subtitle", "Crear una nueva cuenta segura" },
            { "reg_lbl_user", "NUEVO USUARIO" },
            { "reg_lbl_pass", "CONTRASEÑA" },
            { "reg_btn_create", "CREAR CUENTA" },
            { "reg_btn_back", "Volver al Login" },
            { "reg_err_len", "Usuario: Min 3 letras.\nPass: Min 4 letras." },
            { "reg_err_exists", "El usuario ya existe." },
            { "reg_msg_code", "¡Cuenta Creada! GUARDA TU CÓDIGO:" },
            { "reg_msg_login", "Registro exitoso!" },
            { "cfg_btn_reset", "⚠️ Eliminar Cuenta" },
            { "btn_exit_user", "Salir ({0})" },
            { "time_less_5s", "Menos de 5 segundos" },
            { "time_approx_seconds", "Aprox. {0} segundos" },
            { "time_approx_minute", "Aprox. 1 minuto" },
            { "time_approx_minutes", "Aprox. {0} minutos" },
            { "time_approx_hours_mins", "Aprox. {0}h {1}m" },
            { "prescan_title_warning", "⚠️ Advertencia: Gran Volumen" },
            { "prescan_title_summary", "🛡️ Resumen de Seguridad" },
            { "prescan_lbl_files", "ARCHIVOS" },
            { "prescan_lbl_size", "TAMAÑO TOTAL" },
            { "prescan_lbl_time", "TIEMPO EST." },
            { "prescan_large_warning", "⚠️ Aviso: Gran volumen detectado. El cifrado se realizará en lotes transaccionales (Two-Phase Commit) para garantizar cero pérdida de datos." },
            { "prescan_normal_summary", "🛡️ Máxima Seguridad: La carpeta será protegida con cifrado militar AES-256 CTR e integridad autenticada." },
            { "prescan_junk_info", "\n🧹 Filtro Inteligente: {0:N0} archivo(s) temporal(es) excluido(s) para prevenir bloqueos." },
            { "prescan_prompt", "¿Deseas iniciar la encriptación ahora?" },
            { "prescan_btn_proceed", "🔒 INICIAR CIFRADO" },
            { "cfg_sub", "Administra el idioma de la aplicación, el arranque del sistema y los datos criptográficos locales." },
            { "cfg_badge_system", "⚙ PREFERENCIAS DEL SISTEMA" },
            { "cfg_badge_security", "🔒 SEGURIDAD LOCAL" },
            { "cfg_startup_title", "Iniciar con Windows" },
            { "cfg_startup_sub", "Ejecutar FolderLocker minimizado en la bandeja al encender el equipo." },
            { "cfg_junk_title", "Filtro de Archivos Innecesarios" },
            { "cfg_junk_sub", "Omitir y sanear archivos thumbs.db, desktop.ini, .tmp y bloqueos temporales." },
            { "opt_autolock_disabled", "Desactivado" },
            { "opt_autolock_1min", "1 minuto (Prueba)" },
            { "opt_autolock_3min", "3 minutos" },
            { "opt_autolock_5min", "5 minutos (Recomendado)" },
            { "opt_autolock_10min", "10 minutos" },
            { "opt_autolock_15min", "15 minutos" },
            { "opt_autolock_30min", "30 minutos" },
            { "cfg_danger_title", "Restablecimiento de Fábrica" },
            { "cfg_danger_sub", "Elimina la base de datos de usuarios local y restablece la suite." },
            { "cfg_btn_reset_label", "RESTABLECER" },
            { "cfg_sec_dev", "ACERCA DE Y CRÉDITOS" },
            { "cfg_dev_sub", "Desarrollado con Dokan & AES-256 CTR • Arquitectura de Cifrado Atómico" },
            { "cfg_btn_credits_label", "CRÉDITOS" },
            { "cfg_footer_label", "FolderLocker Security Suite • Build 2026.1 • Suite Criptográfica Segura" },
            { "sub_virtual_mount", "Monta tus bóvedas como discos duros virtuales en tiempo real sin necesidad de desencriptar." },
            { "tip_virtual_mount", "💡 La unidad virtual aparecerá en Este Equipo y se cifra en tiempo real sin alterar el disco físico." },
            { "count_vaults_zero", "0 BÓVEDAS" },
            { "count_vaults_one", "1 BÓVEDA" },
            { "count_vaults_many", "{0} BÓVEDAS" },
            { "count_vaults_found", "{0}/{1} ENCONTRADAS" },
            { "lbl_drop_hint", "(Arrastra y suelta aquí o examina)" },
            { "lbl_pass_hint", "🛡️ Las llaves se generan localmente con Argon2id. Tu contraseña nunca se almacena en texto plano." },
            { "lbl_guarantee_atomic", "⚡ Protección Atómica: Operaciones transaccionales. Cero corrupción ante cortes o apagones." },
            { "lbl_guarantee_decrypt", "⚡ Descifrado Seguro: Los archivos y subdirectorios volverán a su estado y formato original sin pérdidas." },
            { "manual_sub", "Aprende a cifrar carpetas, montar discos virtuales y proteger tu privacidad." },
            { "manual_badge_guide", "📖 GUÍA DE USUARIO" },
            { "manual_badge_practices", "🛡 MEJORES PRÁCTICAS" },
            { "man_card1_title", "1. CÓMO PROTEGER UNA CARPETA" },
            { "man_card1_step1", "• Dirígete a la pestaña 'Proteger' en el Centro de Seguridad." },
            { "man_card1_step2", "• Selecciona tu carpeta con el botón 'Examinar...' o simplemente arrástrala a la ventana." },
            { "man_card1_step3", "• Ingresa tu contraseña maestra y pulsa 'Iniciar Bloqueo'. Tus archivos serán cifrados con AES-256 CTR militar y Two-Phase Commit." },
            { "man_card2_title", "2. ACCEDER A LOS ARCHIVOS (ABRIR BÓVEDA)" },
            { "man_card2_step1", "• Ve a la sección 'Abrir Bóveda' en el menú lateral izquierdo." },
            { "man_card2_step2", "• Selecciona tu carpeta encriptada y escoge una letra de disco virtual (ej. M:)." },
            { "man_card2_step3", "• Introduce tu contraseña maestra. Tu bóveda aparecerá como un disco duro en Este Equipo para que edites tus archivos en tiempo real sin tener que desencriptar." },
            { "man_card3_title", "3. RESTAURAR (QUITAR PROTECCIÓN)" },
            { "man_card3_step1", "• En el Centro de Seguridad, pulsa la pestaña superior 'Restaurar'." },
            { "man_card3_step2", "• Selecciona la carpeta protegida de la lista y haz clic en 'Restaurar y Desencriptar'." },
            { "man_card3_step3", "• La carpeta volverá a su estado normal visible y todos tus archivos quedarán completamente desencriptados sin alteraciones." },
            { "man_card4_title", "4. ADVERTENCIAS CRÍTICAS DE SEGURIDAD (LEER OBLIGATORIAMENTE)" },
            { "man_card4_step1", "⚠️ ¡NUNCA entres a la carpeta oculta para pegar o borrar archivos manualmente! Se corromperán al intentar desencriptarlos." },
            { "man_card4_step2", "⚠️ Usa siempre la unidad virtual (Letra:) para editar tus archivos de forma segura y transparente." },
            { "man_card4_step3", "⚠️ NO borres los archivos 'dir.idx' ni 'locker.id'; contienen los mapas de cifrado y perderías el acceso a la bóveda." },
            { "man_card4_step4", "⚠️ Guarda tu código REC en un lugar seguro. Si olvidas tu clave y no tienes tu código, no existe forma matemática de recuperar los datos." },
            { "man_card4_step5", "⚠️ NO apagues el equipo ni desconectes el disco mientras se esté cifrando o restaurando una carpeta con muchos archivos." },
            { "cred_badge_dev", "👨‍💻 DESARROLLADOR" },
            { "cred_badge_suite", "🚀 FOLDERLOCKER SUITE" },
            { "cred_title", "CRÉDITOS Y DESARROLLADOR" },
            { "cred_author_info", "David Armando Platas\nLead Software Engineer & Security Architect\n\nContacto: davarman10@gmail.com" },
            { "cred_desc", "FolderLocker Security Suite v5.2 • 2026\nDesarrollado con C#, .NET 8, Dokan Mirror Driver & AES-256 CTR Atómico." },
            { "cred_btn_github", "🌐 Visitar GitHub" },
            { "cred_btn_back", "⬅ Volver a Configuración" },
            { "login_err_user_first", "Escribe tu usuario primero." },
            { "login_branding_desc", "Grado de Seguridad Militar AES-256 CTR\nAcceso transparente mediante Unidad Virtual Dokan\nProtección absoluta 'Zero-Knowledge'" },
            { "setup_err_empty", "La contraseña no puede estar vacía." },
            { "setup_err_match", "Las contraseñas no coinciden." },
            { "title_welcome", "Bienvenido" },
            { "title_busy", "Operación en Curso" },
            { "title_empty_folder", "Carpeta Vacía" },
            { "title_security_validation", "Validación de Seguridad" },
            { "title_restore_validation", "Validación de Restauración" },
            { "title_confirm_cancel", "Confirmar Cancelación" },
            { "title_system_busy", "Sistema Ocupado" },
            { "title_mount_error", "Error al Montar" },
            { "title_critical_error", "Error Crítico" },
            { "msg_busy_operation", "Ya hay una operación de cifrado en curso. Por favor espera a que finalice." },
            { "msg_empty_folder", "La carpeta está vacía o no contiene archivos válidos para proteger." },
            { "msg_cant_mount_busy", "Hay una operación de cifrado en curso en el sistema. Por seguridad, espera a que termine antes de montar unidades virtuales." },
            { "msg_cant_action_busy", "Hay una operación de cifrado o descifrado en curso.\n\nPor seguridad para evitar la corrupción de archivos, espera a que finalice." },
            { "msg_cant_logout_busy", "No puedes cerrar sesión mientras se estén procesando archivos." },
            { "msg_cant_reset_busy", "No puedes restablecer datos mientras se estén procesando archivos." },
            { "msg_cant_close_busy", "Hay una operación de cifrado o descifrado en curso.\n\nPor seguridad para evitar daños o pérdida de datos, no puedes cerrar la aplicación hasta que termine." },
            { "msg_cant_add_busy", "No puedes agregar otra carpeta mientras hay una operación de cifrado en curso." },
            { "err_protect_failed", "Error al proteger carpeta" },
            { "err_restore_failed", "Error al restaurar" },
            { "err_folder_mounted_dokan", "Esta carpeta está actualmente montada como unidad virtual.\n\nPor favor desmonta la unidad virtual antes de intentar protegerla o modificar su cifrado." },
            { "err_insufficient_permissions", "No tienes permisos suficientes de escritura en esta carpeta:\n{0}\n\nAsegúrate de tener permisos de administrador o de que los archivos no estén bloqueados." },
            { "err_insufficient_disk_space", "Espacio insuficiente en disco.\n\nSe requieren aproximadamente {0} libres para un cifrado atómico seguro con Two-Phase Commit, pero solo hay {1} disponibles en la unidad {2}." },
        };
        #endregion

        // =============================================================
        // 2. ENGLISH (EN)
        // =============================================================
        #region DICCIONARIO INGLÉS (EN)
        private static readonly Dictionary<string, string> EN = new Dictionary<string, string>
        {
            { "menu_protect", "🔒  LOCK FOLDER" },
            { "menu_unlock", "🔓  OPEN VAULT" },
            { "menu_files", "📂  MY FILES" },
            { "menu_config", "⚙️ SETTINGS" },
            { "menu_manual", "📘  USER MANUAL" },
            { "menu_exit", "🚪  EXIT" },
            { "title_main", "Security Center" },
            { "app_subtitle", "Security Suite" },
            { "tab_restore", "🔓  RESTORE" },
            { "lbl_target", "TARGET FOLDER (CHOOSE DIRECTORY)" },
            { "lbl_pass", "ENCRYPTION KEY (PASSWORD)" },
            { "link_forgot", "Forgot password?" },
            { "btn_browse", "Browse..." },
            { "btn_lock", "START LOCKING" },
            { "lbl_path_protected", "CURRENT PROTECTED PATH" },
            { "btn_decrypt", "DECRYPT PERMANENTLY" },
            { "title_virtual", "Secure Virtual Access" },
            { "lbl_vaults", "MY VAULTS (SELECT ONE)" },
            { "placeholder_search_vault", "Search vault by name or path..." },
            { "lbl_no_vaults_found", "No vaults match your search criteria." },
            { "lbl_no_vaults_available", "You have no protected vaults yet." },
            { "lbl_drive", "DRIVE LETTER" },
            { "lbl_mount_pass", "ENCRYPTION KEY (PASSWORD)" },
            { "btn_mount", "OPEN VIRTUAL DRIVE" },
            { "btn_unmount", "CLOSE DRIVE" },
            { "setup_title", "WELCOME TO LOCKER" },
            { "setup_sub", "Initial security setup." },
            { "setup_lbl_create", "CREATE MASTER PASSWORD" },
            { "setup_lbl_confirm", "CONFIRM PASSWORD" },
            { "setup_note", "⚠️ Remember your username and password. If you forget them and do not have the recovery code,\nyour files will be irrecoverable." },
            { "setup_btn", "ESTABLISH SECURITY" },
            { "config_title", "SETTINGS" },
            { "config_lbl_lang", "IDIOMA" },
            { "config_chk_start", "Start FolderLocker with Windows (Minimized)" },
            { "cfg_sec_general", "🌍  GENERAL" },
            { "cfg_sec_system", "💻  SYSTEM" },
            { "cfg_autolock_title", "Inactivity Auto-Lock" },
            { "cfg_autolock_sub", "Lock session and unmount virtual drives after idle time." },
            { "msg_autolock_triggered", "🔒 Session locked automatically due to inactivity." },
            { "cfg_sec_data", "🛡️  PRIVACY & DATA" },
            { "cfg_btn_clear", "CLEAR FOLDER HISTORY" },
            { "cfg_msg_clear", "Are you sure? Saved folder locations will be forgotten (files are not deleted)." },
            { "cfg_msg_reset", "⚠️ This will delete your account and settings.\nMake sure you have decrypted your folders before deleting.\nContinue?" },
            { "cfg_done", "Operation successful." },
            { "manual_title", "QUICK USER GUIDE" },
            { "manual_text", "1. PROTECT FOLDER:\n    - Go to the 'Protect' tab.\n    - Choose a folder and enter your password.\n    - The folder will be hidden and encrypted.\n\n2. ACCESS FILES (OPEN VAULT):\n    - Go to 'Open Vault' in the side menu.\n    - Select your folder from the list.\n    - Choose a drive letter (e.g.: M:) and enter your password.\n    - It will open as a secure virtual drive.\n\n3. RESTORE (REMOVE PROTECTION):\n    - Inside the 'Protect' tab there is the 'Restore' option.\n    - Select the folder to restore and enter your password.\n    - The folder will return to normal, it will be decrypted and made visible.\n\n4. ⚠️ CRITICAL WARNINGS (READ):\n    - NEVER enter the hidden folder to paste files manually! They will be damaged when attempting to decrypt them.\n    - Use the virtual drive (Letter:) to edit your files. Alternatively, decrypt the folder, create, move, or edit your new files, and then encrypt it again.\n    - DO NOT delete the 'dir.idx' or 'locker.id' files, or you will lose access to everything.\n    - If you forget your password AND lose your REC code, there is no human way to recover your data.\n    - DO NOT shut down the computer while a large folder is being protected/restored, or data loss may occur." },
            { "msg_select_dir", "Please select a directory." },
            { "msg_pass_wrong", "Incorrect password." },
            { "msg_already_list", "This folder is already in your list." },
            { "msg_rec_title", "Smart Recovery" },
            { "msg_rec_text", "Folder Recovered!\nThis folder was already protected.\nIt has been added to your list without modifying files." },
            { "msg_lock_success", "Folder encrypted and added to the vault." },
            { "msg_select_restore", "Please select a folder." },
            { "msg_confirm_decrypt", "Decrypt folder:\n{0}?" },
            { "msg_decrypt_success", "Folder successfully restored at:" },
            { "msg_mount_select", "Select a folder from the list." },
            { "msg_mount_select_drive", "Select a drive" },
            { "err_not_owner", "⛔ ACCESS DENIED\nThis folder belongs to another user" },
            { "msg_mount_active", "This folder is already open on drive {0}" },
            { "msg_drive_busy", "Drive {0} is busy. Choose another." },
            { "msg_mount_success", "Drive {0} is ACTIVE.\nYou can access it from the 'My Files' menu." },
            { "msg_unmount_select", "Select which folder to close from the list." },
            { "msg_unmount_success", "Drive {0} closed successfully." },
            { "msg_unmount_error", "Problem unmounting. Check for open files." },
            { "msg_no_vault", "No open vaults found. Mount one first." },
            { "err_drag_folder", "Please drag a folder, not a single file." },
            { "err_drag_folder_title", "Folders Only" },
            { "err_root", "⚠️ CRITICAL ERROR ⚠️\nYou are trying to lock a WHOLE DRIVE ({0}).\nThis would corrupt the drive.\n\nSOLUTION: Create a folder inside the drive and select that." },
            { "err_self", "⛔ AUTO-LOCK PREVENTED\nYou cannot lock the folder where this program is running." },
            { "err_sys", "⛔ SYSTEM PROTECTION\nModifying Windows system folders is not allowed." },
            { "err_security_title", "Operation Aborted by Security" },
            { "status_processing", "⏳ PROCESSING..." },
            { "status_decrypting", "⏳ DECRYPTING..." },
            { "tray_working", "Locker - Working" },
            { "tray_working_desc", "Process running in background. Double click here to view progress." },
            { "tray_done", "Locker - Finished" },
            { "tray_done_lock", "Folder locked successfully." },
            { "tray_done_decrypt", "Folder restored successfully." },
            { "tray_minimized_title", "FolderLocker Active" },
            { "tray_minimized_msg", "The application is running in the background." },
            { "tray_menu_open", "Open Locker" },
            { "tray_menu_exit", "Exit" },
            { "btn_accept", "ACCEPT" },
            { "btn_cancel", "CANCEL" },
            { "btn_yes", "YES, CONTINUE" },
            { "btn_ready", "DONE" },
            { "prog_title", "PROCESSING VAULT..." },
            { "prog_init", "Starting..." },
            { "prog_hide_btn", "👁️ BACKGROUND" },
            { "prog_pause", "⏸️  PAUSE" },
            { "prog_resume", "▶️  RESUME" },
            { "prog_cancel", "🛑  CANCEL" },
            { "prog_paused", "⏸️ Operation paused by user" },
            { "prog_confirm_cancel", "Do you want to cancel the current operation?\n\nFiles processed so far will remain protected." },
            { "msg_op_cancelled", "The operation was cancelled by the user. Remaining files were not modified." },
            { "prog_file_lbl", "Processing: {0}" },
            { "prog_done", "Finishing..." },
            { "status_done", "Done!" },
            { "title_info", "Info" },
            { "title_confirm", "Confirm" },
            { "title_error", "Error" },
            { "title_warning", "Warning" },
            { "title_success", "Success" },
            { "title_security", "Security" },
            { "val_min_chars", "Min: 4 chars." },
            { "val_no_match", "Passwords do not match." },
            { "val_save_code", "SAVE THIS CODE IN A SAFE PLACE:" },
            { "rec_prompt_title", "Account Recovery" },
            { "rec_prompt_msg", "Enter Recovery Code (REC-XXXX):" },
            { "rec_success_msg", "Success! Your password is:" },
            { "rec_fail_msg", "Invalid or incorrect code." },
            // LOGIN & REGISTER
            { "login_title", "LOGIN" },
            { "login_lbl_user", "USERNAME" },
            { "login_lbl_pass", "PASSWORD" },
            { "login_btn_enter", "SIGN IN" },
            { "login_btn_reg", "Create New Account" },
            { "login_err_auth", "Invalid username or password." },
            { "login_welcome", "Welcome, {0}!" },

            { "reg_title", "REGISTER" },
            { "reg_subtitle", "Create a new secure account" },
            { "reg_lbl_user", "NEW USERNAME" },
            { "reg_lbl_pass", "PASSWORD" },
            { "reg_btn_create", "CREATE ACCOUNT" },
            { "reg_btn_back", "Back to Login" },
            { "reg_err_len", "User: Min 3 chars.\nPass: Min 4 chars." },
            { "reg_err_exists", "Username already exists." },
            { "reg_msg_code", "Account Created! SAVE YOUR CODE:" },
            { "reg_msg_login", "Registration successful!" },
            { "login_chk_remember", "Remember Me" },
            { "msg_logout_confirm", "Log out of current session?" },
            { "cfg_btn_reset", "⚠️ Delete Account" },
            { "btn_exit_user", "Exit ({0})" },
            { "str_0", "Very Weak" },
            { "str_1", "Weak" },
            { "str_2", "Average" },
            { "str_3", "Good" },
            { "str_4", "Strong" },
            { "str_5", "Excellent" },
            { "tray_min_title", "FolderLocker Minimized" },
            { "tray_min_click", "Program minimized, click here to open." },
            { "time_less_5s", "Less than 5 seconds" },
            { "time_approx_seconds", "Approx. {0} seconds" },
            { "time_approx_minute", "Approx. 1 minute" },
            { "time_approx_minutes", "Approx. {0} minutes" },
            { "time_approx_hours_mins", "Approx. {0}h {1}m" },
            { "prescan_title_warning", "⚠️ Warning: Large File Volume" },
            { "prescan_title_summary", "🛡️ Security Summary" },
            { "prescan_lbl_files", "FILES" },
            { "prescan_lbl_size", "TOTAL SIZE" },
            { "prescan_lbl_time", "EST. TIME" },
            { "prescan_large_warning", "⚠️ Notice: Large folder detected. The encryption process runs in transactional batches (Two-Phase Commit) to guarantee zero file loss." },
            { "prescan_normal_summary", "🛡️ Maximum Security: Folder will be protected with military AES-256 CTR encryption and authenticated integrity." },
            { "prescan_junk_info", "\n🧹 Smart Filter: {0:N0} temporary/lock file(s) excluded (thumbs.db, .tmp, etc.)" },
            { "prescan_prompt", "Do you want to proceed with encryption?" },
            { "prescan_btn_proceed", "🔒 PROCEED ENCRYPTION" },
            { "cfg_sub", "Manage language settings, system startup, and local cryptographic database." },
            { "cfg_badge_system", "⚙ SYSTEM PREFERENCES" },
            { "cfg_badge_security", "🔒 LOCAL SECURITY" },
            { "cfg_startup_title", "Start with Windows" },
            { "cfg_startup_sub", "Launch FolderLocker minimized in the background on startup." },
            { "cfg_junk_title", "Junk / Temp File Filter" },
            { "cfg_junk_sub", "Skip and clean thumbs.db, desktop.ini, .tmp and temporary locks." },
            { "opt_autolock_disabled", "Disabled" },
            { "opt_autolock_1min", "1 minute (Test)" },
            { "opt_autolock_3min", "3 minutes" },
            { "opt_autolock_5min", "5 minutes (Recommended)" },
            { "opt_autolock_10min", "10 minutes" },
            { "opt_autolock_15min", "15 minutes" },
            { "opt_autolock_30min", "30 minutes" },
            { "cfg_danger_title", "Factory Reset" },
            { "cfg_danger_sub", "Deletes local user database and restores the suite to initial state." },
            { "cfg_btn_reset_label", "RESET" },
            { "cfg_sec_dev", "ABOUT & CREDITS" },
            { "cfg_dev_sub", "Powered by Dokan & AES-256 CTR • Atomic Encryption Architecture" },
            { "cfg_btn_credits_label", "CREDITS" },
            { "cfg_footer_label", "FolderLocker Security Suite • Build 2026.1 • Secure Cryptographic Suite" },
            { "sub_virtual_mount", "Mount your protected vaults as virtual hard drives on-the-fly without decrypting." },
            { "tip_virtual_mount", "💡 The virtual drive appears in Windows Explorer and encrypts seamlessly in real-time." },
            { "count_vaults_zero", "0 VAULTS" },
            { "count_vaults_one", "1 VAULT" },
            { "count_vaults_many", "{0} VAULTS" },
            { "count_vaults_found", "{0}/{1} FOUND" },
            { "lbl_drop_hint", "(Drag & drop folder here or browse)" },
            { "lbl_pass_hint", "🛡️ Encryption keys are generated locally. Your password is never stored in plain text." },
            { "lbl_guarantee_atomic", "⚡ Atomic Protection: Interrupted operations roll back cleanly without corrupted files." },
            { "lbl_guarantee_decrypt", "⚡ Secure Decryption: Files and subdirectories will be completely restored to original format." },
            { "manual_sub", "Learn how to encrypt, mount virtual drives, and protect your private data." },
            { "manual_badge_guide", "📖 USER GUIDE" },
            { "manual_badge_practices", "🛡 BEST PRACTICES" },
            { "man_card1_title", "1. HOW TO PROTECT A FOLDER" },
            { "man_card1_step1", "• Go to the 'Protect' tab in the Security Center." },
            { "man_card1_step2", "• Select your folder using 'Browse...' or drag and drop it directly onto the window." },
            { "man_card1_step3", "• Enter your master password and click 'Start Protection'. Your files will be secured with military-grade AES-256 CTR and Two-Phase Commit." },
            { "man_card2_title", "2. ACCESS FILES (OPEN VAULT)" },
            { "man_card2_step1", "• Navigate to 'Open Vault' in the left sidebar menu." },
            { "man_card2_step2", "• Select your encrypted folder and pick a virtual drive letter (e.g. M:)." },
            { "man_card2_step3", "• Enter your master password. The vault will mount as a virtual hard drive in Windows Explorer for seamless real-time access without decrypting." },
            { "man_card3_title", "3. RESTORE (REMOVE PROTECTION)" },
            { "man_card3_step1", "• In the Security Center, select the upper 'Restore' tab." },
            { "man_card3_step2", "• Pick the protected folder from the list and click 'Restore & Decrypt'." },
            { "man_card3_step3", "• The folder will return to normal visible state and all files will be fully restored without modifications." },
            { "man_card4_title", "4. CRITICAL SECURITY WARNINGS (MUST READ)" },
            { "man_card4_step1", "⚠️ NEVER enter the hidden folder to paste or modify files manually! They will be corrupted upon decryption." },
            { "man_card4_step2", "⚠️ Always use the virtual drive (Drive Letter:) to view and edit files transparently." },
            { "man_card4_step3", "⚠️ DO NOT delete 'dir.idx' or 'locker.id' files; they store the encrypted catalog required to access your vault." },
            { "man_card4_step4", "⚠️ Save your REC code safely. If you lose both your password and REC key, recovery is cryptographically impossible." },
            { "man_card4_step5", "⚠️ DO NOT shut down the PC or unplug external storage during encryption or batch decryption operations." },
            { "cred_badge_dev", "👨‍💻 DEVELOPER" },
            { "cred_badge_suite", "🚀 FOLDERLOCKER SUITE" },
            { "cred_title", "CREDITS & DEVELOPER" },
            { "cred_author_info", "David Armando Platas\nLead Software Engineer & Security Architect\n\nContact: davarman10@gmail.com" },
            { "cred_desc", "FolderLocker Security Suite v5.2 • 2026\nBuilt with C#, .NET 8, Dokan Mirror Driver & Atomic AES-256 CTR." },
            { "cred_btn_github", "🌐 Visit GitHub" },
            { "cred_btn_back", "⬅ Back to Settings" },
            { "login_err_user_first", "Please enter your username first." },
            { "login_branding_desc", "Military Grade AES-256 CTR Security\nTransparent access via Dokan Virtual Drive\nZero-Knowledge cryptographic architecture" },
            { "setup_err_empty", "Password cannot be empty." },
            { "setup_err_match", "Passwords do not match." },
            { "title_welcome", "Welcome" },
            { "title_busy", "Operation in Progress" },
            { "title_empty_folder", "Empty Folder" },
            { "title_security_validation", "Security Validation" },
            { "title_restore_validation", "Restore Validation" },
            { "title_confirm_cancel", "Confirm Cancellation" },
            { "title_system_busy", "System Busy" },
            { "title_mount_error", "Mount Error" },
            { "title_critical_error", "Critical Error" },
            { "msg_busy_operation", "An encryption or decryption operation is already in progress. Please wait for it to complete." },
            { "msg_empty_folder", "The folder is empty or does not contain valid files to protect." },
            { "msg_cant_mount_busy", "An encryption operation is currently in progress. For security, please wait until it finishes before mounting virtual drives." },
            { "msg_cant_action_busy", "An encryption or decryption operation is in progress.\n\nTo prevent file corruption, please wait for it to complete." },
            { "msg_cant_logout_busy", "You cannot log out while files are being processed." },
            { "msg_cant_reset_busy", "You cannot reset database while files are being processed." },
            { "msg_cant_close_busy", "An operation is currently in progress.\n\nTo prevent data loss or damage, you cannot close the application until it completes." },
            { "msg_cant_add_busy", "Cannot add another folder while an encryption operation is in progress." },
            { "err_protect_failed", "Error protecting folder" },
            { "err_restore_failed", "Error restoring folder" },
            { "err_folder_mounted_dokan", "This folder is currently mounted as a virtual drive.\n\nPlease unmount the virtual drive before protecting or modifying its encryption." },
            { "err_insufficient_permissions", "Insufficient write permissions in this folder:\n{0}\n\nEnsure you have administrator rights and files are not locked." },
            { "err_insufficient_disk_space", "Insufficient disk space.\n\nApproximately {0} of free space is required for safe atomic encryption (Two-Phase Commit), but only {1} is available on drive {2}." },
        };
        #endregion

        // =============================================================
        // 3. PORTUGUÊS (PT)
        // =============================================================
        #region DICCIONARIO PORTUGUÉS (PT)
        private static readonly Dictionary<string, string> PT = new Dictionary<string, string>
        {
            { "menu_protect", "🔒  PROTEGER" },
            { "menu_unlock", "🔓  ABRIR COFRE" },
            { "menu_files", "📂  MEUS ARQUIVOS" },
            { "menu_config", "⚙️ CONFIGURAÇÕES" },
            { "menu_manual", "📘  MANUAL" },
            { "menu_exit", "🚪  SAIR" },
            { "title_main", "Centro de Segurança" },
            { "app_subtitle", "Suíte de Segurança" },
            { "tab_restore", "🔓  RESTAURAR" },
            { "lbl_target", "PASTA ALVO (ESCOLHER DIRETÓRIO)" },
            { "lbl_pass", "CHAVE DE CRIPTOGRAFIA (SENHA)" },
            { "link_forgot", "Esqueceu a senha?" },
            { "btn_browse", "Procurar..." },
            { "btn_lock", "INICIAR BLOQUEIO" },
            { "lbl_path_protected", "CAMINHO PROTEGIDO ATUAL" },
            { "btn_decrypt", "DESCRIPTOGRAFAR PERMANENTEMENTE" },
            { "title_virtual", "Acesso Virtual Seguro" },
            { "lbl_vaults", "MEUS COFRES (SELECIONE UM)" },
            { "lbl_drive", "LETRA DA UNIDADE" },
            { "lbl_mount_pass", "CHAVE DE CRIPTOGRAFIA (SENHA)" },
            { "btn_mount", "ABRIR UNIDADE VIRTUAL" },
            { "btn_unmount", "FECHAR UNIDADE" },
            { "setup_title", "BEM-VINDO AO LOCKER" },
            { "setup_sub", "Configuração inicial de segurança." },
            { "setup_lbl_create", "CRIE SUA SENHA MESTRA" },
            { "setup_lbl_confirm", "CONFIRME A SENHA" },
            { "setup_note", "⚠️ Lembre-se do seu nome de usuário e senha. Se você esquecer e não tiver o código de recuperação,\nseus arquivos serão irrecuperáveis." },
            { "setup_btn", "ESTABELECER SEGURANÇA" },
            { "config_title", "CONFIGURAÇÕES" },
            { "config_lbl_lang", "IDIOMA" },
            { "config_chk_start", "Iniciar FolderLocker com Windows (Minimizado)" },
            { "cfg_sec_general", "🌍  GERAL" },
            { "cfg_sec_system", "💻  SISTEMA" },
            { "cfg_sec_data", "🛡️  PRIVACIDADE E DADOS" },
            { "cfg_btn_clear", "LIMPAR HISTÓRICO DE ROTAS" },
            { "cfg_msg_clear", "Tem certeza? As localizações salvas serão esquecidas (arquivos não são apagados)." },
            { "cfg_msg_reset", "⚠️ Isso excluirá sua conta e configurações.\nCertifique-se de ter descriptografado suas pastas antes de excluir.\nContinuar?" },
            { "cfg_done", "Operação realizada com sucesso." },
            { "manual_title", "GUIA RÁPIDO DO USUÁRIO" },
            { "manual_text", "1. PROTEGER PASTA:\n    - Vá para a aba 'Proteger'.\n    - Escolha uma pasta e insira sua senha.\n    - A pasta será oculta e criptografada.\n\n2. ACESSAR ARQUIVOS (ABRIR COFRE):\n    - Vá para 'Abrir Cofre' no menu lateral.\n    - Selecione sua pasta na lista.\n    - Escolha uma letra (ex: M:) e insira sua senha.\n    - Será aberto como um disco virtual seguro.\n\n3. RESTAURAR (REMOVER PROTEÇÃO):\n    - Dentro da aba 'Proteger' está a opção 'Restaurar'.\n    - Selecione a pasta a restaurar e insira sua senha.\n    - A pasta voltará ao normal, será descriptografada e ficará visível.\n\n4. ⚠️ AVISOS CRÍTICOS (LER):\n    - NUNCA entre na pasta oculta para colar arquivos manualmente! Eles serão danificados ao tentar descriptografá-los.\n    - Use a unidade virtual (Letra:) para editar seus arquivos. Ou, em alternativa, descriptografe a pasta, crie, mova ou edite seus novos arquivos e, em seguida, criptografe-a novamente.\n    - NÃO apague os arquivos 'dir.idx' ou 'locker.id', ou você perderá o acesso a tudo.\n    - Se você esquecer sua senha E perder seu código REC, não há como recuperar seus dados.\n    - NÃO DESLIGUE o computador enquanto uma pasta grande estiver sendo protegida/restaurada, pode haver perda de dados." },
            { "msg_select_dir", "Selecione um diretório." },
            { "msg_pass_wrong", "Senha incorreta." },
            { "msg_already_list", "Esta pasta já está na sua lista." },
            { "msg_rec_title", "Recuperação Inteligente" },
            { "msg_rec_text", "Pasta Recuperada!\nEsta pasta já estava protegida.\nFoi adicionada à sua lista sem modificar arquivos." },
            { "msg_lock_success", "Pasta criptografada e adicionada ao cofre." },
            { "msg_select_restore", "Por favor, selecione uma pasta." },
            { "msg_confirm_decrypt", "Descriptografar a pasta:\n{0}?" },
            { "msg_decrypt_success", "Pasta restaurada com sucesso em:" },
            { "msg_mount_select", "Selecione uma pasta da lista." },
            { "msg_mount_select_drive", "Selecione uma unidade" },
            { "err_not_owner", "⛔ ACESSO NEGADO\nEsta pasta pertence a outro usuário" },
            { "msg_mount_active", "Esta pasta já está aberta na unidade {0}" },
            { "msg_drive_busy", "A letra {0} já está em uso. Escolha outra." },
            { "msg_mount_success", "Unidade {0} ATIVA.\nVocê pode acessá-la no menu 'Meus Arquivos'." },
            { "msg_unmount_select", "Selecione na lista qual pasta deseja fechar." },
            { "msg_unmount_success", "Unidade {0} fechada corretamente." },
            { "msg_unmount_error", "Problema ao desmontar. Verifique se há arquivos abertos." },
            { "msg_no_vault", "Nenhum cofre aberto. Monte um primeiro." },
            { "err_drag_folder", "Por favor, arraste uma pasta, não um arquivo." },
            { "err_drag_folder_title", "Apenas Pastas" },
            { "err_root", "⚠️ ERRO CRÍTICO ⚠️\nVocê está tentando bloquear um DISCO INTEIRO ({0}).\nIsso corromperia a unidade.\nSOLUÇÃO: Crie uma pasta dentro do disco e selecione-a." },
            { "err_self", "⛔ AUTO-BLOQUEIO PREVENIDO\nVocê não pode bloquear a pasta onde este programa está rodando." },
            { "err_sys", "⛔ PROTEÇÃO DE SISTEMA\nNão é permitido modificar pastas do Windows." },
            { "err_security_title", "Operação Abortada por Segurança" },
            { "status_processing", "⏳ PROCESSANDO..." },
            { "status_decrypting", "⏳ DESCRIPTOGRAFANDO..." },
            { "tray_working", "Locker - Trabalhando" },
            { "tray_working_desc", "O processo continua em segundo plano. Clique duas vezes para ver." },
            { "tray_done", "Locker - Finalizado" },
            { "tray_done_lock", "A pasta foi bloqueada com sucesso." },
            { "tray_done_decrypt", "Pasta restaurada corretamente." },
            { "tray_minimized_title", "FolderLocker Ativo" },
            { "tray_minimized_msg", "O aplicativo continua rodando em segundo plano." },
            { "tray_menu_open", "Abrir Locker" },
            { "tray_menu_exit", "Sair" },
            { "btn_accept", "ACEITAR" },
            { "btn_cancel", "CANCELAR" },
            { "btn_yes", "SIM, CONTINUAR" },
            { "btn_ready", "PRONTO" },
            { "prog_title", "PROCESSANDO COFRE..." },
            { "prog_init", "Iniciando..." },
            { "prog_hide_btn", "⬇️ Ocultar e trabalhar em 2º plano" },
            { "prog_file_lbl", "Processando: {0}" },
            { "prog_done", "Finalizando..." },
            { "status_done", "Feito!" },
            { "title_info", "Informação" },
            { "title_confirm", "Confirmar" },
            { "title_error", "Erro" },
            { "title_warning", "Aviso" },
            { "title_success", "Sucesso" },
            { "title_security", "Segurança" },
            { "val_min_chars", "Mínimo 4 caracteres." },
            { "val_no_match", "As senhas não coincidem." },
            { "val_save_code", "GUARDE ESTE CÓDIGO EM UM LUGAR SEGURO:" },
            { "rec_prompt_title", "Recuperação de Conta" },
            { "rec_prompt_msg", "Digite seu Código de Recuperação (REC-XXXX):" },
            { "rec_success_msg", "Sucesso! Sua senha é:" },
            { "rec_fail_msg", "Código incorreto ou inválido." },
            // LOGIN & REGISTRO
            { "login_title", "ENTRAR" },
            { "login_lbl_user", "USUÁRIO" },
            { "login_lbl_pass", "SENHA" },
            { "login_btn_enter", "ENTRAR" },
            { "login_btn_reg", "Criar Nova Conta" },
            { "login_err_auth", "Usuário ou senha incorretos." },
            { "login_welcome", "Bem-vindo, {0}!" },

            { "reg_title", "REGISTRO" },
            { "reg_subtitle", "Criar uma nova conta segura" },
            { "reg_lbl_user", "NOVO USUÁRIO" },
            { "reg_lbl_pass", "SENHA" },
            { "reg_btn_create", "CRIAR CONTA" },
            { "reg_btn_back", "Voltar para Login" },
            { "reg_err_len", "Usuário: Min 3 letras.\nSenha: Min 4 letras." },
            { "reg_err_exists", "O usuário já existe." },
            { "reg_msg_code", "Conta Criada! GUARDE SEU CÓDIGO:" },
            { "reg_msg_login", "Registro bem-sucedido!" },
            { "login_chk_remember", "Lembrar Usuário" },
            { "msg_logout_confirm", "Sair da sessão atual?" },
            { "cfg_btn_reset", "⚠️ Excluir Conta" },
            { "btn_exit_user", "Sair ({0})" },
            { "str_0", "Muito Fraco" },
            { "str_1", "Fraco" },
            { "str_2", "Normal" },
            { "str_3", "Bom" },
            { "str_4", "Forte" },
            { "str_5", "Excelente" },
            { "tray_min_title", "FolderLocker Minimizado" },
            { "tray_min_click", "Programa minimizado, clique aqui para abrir." },
            { "time_less_5s", "Menos de 5 segundos" },
            { "time_approx_seconds", "Aprox. {0} segundos" },
            { "time_approx_minute", "Aprox. 1 minuto" },
            { "time_approx_minutes", "Aprox. {0} minutos" },
            { "time_approx_hours_mins", "Aprox. {0}h {1}m" },
            { "prescan_title_warning", "⚠️ Aviso: Grande Volume de Arquivos" },
            { "prescan_title_summary", "🛡️ Resumo de Segurança" },
            { "prescan_lbl_files", "ARQUIVOS" },
            { "prescan_lbl_size", "TAMANHO TOTAL" },
            { "prescan_lbl_time", "TEMPO EST." },
            { "prescan_large_warning", "⚠️ Aviso: Grande volume detectado. A criptografia será feita em lotes transacionais (Two-Phase Commit) garantindo integridade total." },
            { "prescan_normal_summary", "🛡️ Segurança Máxima: A pasta será protegida com criptografia militar AES-256 CTR e integridade autenticada." },
            { "prescan_junk_info", "\n🧹 Filtro Inteligente: {0:N0} arquivo(s) temporário(s) excluído(s) para evitar travamentos." },
            { "prescan_prompt", "Deseja iniciar a criptografia agora?" },
            { "prescan_btn_proceed", "🔒 INICIAR CRIPTOGRAFIA" },
            { "cfg_sub", "Gerencie configurações de idioma, inicialização do sistema e dados criptográficos locais." },
            { "cfg_badge_system", "⚙ PREFERÊNCIAS DO SISTEMA" },
            { "cfg_badge_security", "🔒 SEGURANÇA LOCAL" },
            { "cfg_startup_title", "Iniciar com o Windows" },
            { "cfg_startup_sub", "Executar o FolderLocker minimizado na bandeja ao iniciar o sistema." },
            { "cfg_junk_title", "Filtro de Arquivos Temporários" },
            { "cfg_junk_sub", "Ignorar e limpar thumbs.db, desktop.ini, .tmp e travas temporárias." },
            { "cfg_autolock_title", "Bloqueio Automático por Inatividade" },
            { "cfg_autolock_sub", "Bloquear sessão e desmontar discos virtuais após tempo ocioso." },
            { "opt_autolock_disabled", "Desativado" },
            { "opt_autolock_1min", "1 minuto (Teste)" },
            { "opt_autolock_3min", "3 minutos" },
            { "opt_autolock_5min", "5 minutos (Recomendado)" },
            { "opt_autolock_10min", "10 minutos" },
            { "opt_autolock_15min", "15 minutos" },
            { "opt_autolock_30min", "30 minutos" },
            { "cfg_danger_title", "Restauração de Fábrica" },
            { "cfg_danger_sub", "Exclui o banco de dados local e redefine a suíte para o estado inicial." },
            { "cfg_btn_reset_label", "REDEFINIR" },
            { "cfg_sec_dev", "SOBRE E CRÉDITOS" },
            { "cfg_dev_sub", "Desenvolvido com Dokan e AES-256 CTR • Arquitetura de Criptografia Atômica" },
            { "cfg_btn_credits_label", "CRÉDITOS" },
            { "cfg_footer_label", "FolderLocker Security Suite • Build 2026.1 • Suíte Criptográfica Segura" },
            { "sub_virtual_mount", "Monte seus cofres como discos virtuais em tempo real sem precisar descriptografar." },
            { "tip_virtual_mount", "💡 A unidade virtual aparecerá em Este Computador e é criptografada em tempo real." },
            { "count_vaults_zero", "0 COFRES" },
            { "count_vaults_one", "1 COFRE" },
            { "count_vaults_many", "{0} COFRES" },
            { "count_vaults_found", "{0}/{1} ENCONTRADOS" },
            { "lbl_drop_hint", "(Arraste e solte aqui ou procure)" },
            { "lbl_pass_hint", "🛡️ As chaves são geradas localmente. Sua senha nunca é salva em texto simples." },
            { "lbl_guarantee_atomic", "⚡ Proteção Atômica: Operações transacionais sem corrupção de arquivos." },
            { "lbl_guarantee_decrypt", "⚡ Descriptografia Segura: Os arquivos e subdiretórios serão restaurados ao formato original." },
            { "manual_sub", "Aprenda a criptografar pastas, montar discos virtuais e proteger sua privacidade." },
            { "manual_badge_guide", "📖 GUIA DO USUÁRIO" },
            { "manual_badge_practices", "🛡 MELHORES PRÁTICAS" },
            { "man_card1_title", "1. COMO PROTEGER UMA PASTA" },
            { "man_card1_step1", "• Acesse a aba 'Proteger' na Central de Segurança." },
            { "man_card1_step2", "• Selecione sua pasta pelo botão 'Procurar...' ou simplesmente arraste-a para a janela." },
            { "man_card1_step3", "• Digite sua senha mestre e clique em 'Iniciar Bloqueio'. Seus arquivos serão criptografados com AES-256 CTR militar." },
            { "man_card2_title", "2. ACESSAR ARQUIVOS (ABRIR COFRE)" },
            { "man_card2_step1", "• Vá para 'Abrir Cofre' no menu lateral esquerdo." },
            { "man_card2_step2", "• Selecione sua pasta criptografada e escolha uma letra de unidade virtual (ex: M:)." },
            { "man_card2_step3", "• Insira sua senha mestre. O cofre aparecerá como um disco no Windows Explorer para edição em tempo real sem descriptografar." },
            { "man_card3_title", "3. RESTAURAR (REMOVER PROTEÇÃO)" },
            { "man_card3_step1", "• Na Central de Segurança, selecione a aba superior 'Restaurar'." },
            { "man_card3_step2", "• Selecione a pasta protegida na lista e clique em 'Restaurar e Descriptografar'." },
            { "man_card3_step3", "• A pasta voltará ao estado visível normal e todos os arquivos serão totalmente restaurados." },
            { "man_card4_title", "4. AVISOS CRÍTICOS DE SEGURANÇA (LEITURA OBRIGATÓRIA)" },
            { "man_card4_step1", "⚠️ NUNCA acesse a pasta oculta para colar ou modificar arquivos manualmente! Eles serão corrompidos." },
            { "man_card4_step2", "⚠️ Sempre use a unidade virtual (Letra:) para visualizar e editar arquivos de forma segura." },
            { "man_card4_step3", "⚠️ NÃO exclua os arquivos 'dir.idx' ou 'locker.id'; eles contêm o catálogo criptográfico da sua bóveda." },
            { "man_card4_step4", "⚠️ Guarde seu código REC com segurança. Sem a senha e sem o código, a recuperação é matematicamente impossível." },
            { "man_card4_step5", "⚠️ NÃO desligue o computador nem desconecte unidades externas durante operações de criptografia." },
            { "cred_badge_dev", "👨‍💻 DESENVOLVEDOR" },
            { "cred_badge_suite", "🚀 FOLDERLOCKER SUITE" },
            { "cred_title", "CRÉDITOS E DESENVOLVEDOR" },
            { "cred_author_info", "David Armando Platas\nLead Software Engineer & Security Architect\n\nContato: davarman10@gmail.com" },
            { "cred_desc", "FolderLocker Security Suite v5.2 • 2026\nDesenvolvido com C#, .NET 8, Dokan Driver e AES-256 CTR Atômico." },
            { "cred_btn_github", "🌐 Visitar GitHub" },
            { "cred_btn_back", "⬅ Voltar para Configurações" },
            { "login_err_user_first", "Por favor, digite seu usuário primeiro." },
            { "login_branding_desc", "Segurança Militar AES-256 CTR\nAcesso transparente via Unidade Virtual Dokan\nArquitetura de Conhecimento Zero" },
            { "setup_err_empty", "A senha não pode ficar vazia." },
            { "setup_err_match", "As senhas não coincidem." },
            { "title_welcome", "Bem-vindo" },
            { "title_busy", "Operação em Andamento" },
            { "title_empty_folder", "Pasta Vazia" },
            { "title_security_validation", "Validação de Segurança" },
            { "title_restore_validation", "Validação de Restauração" },
            { "title_confirm_cancel", "Confirmar Cancelamento" },
            { "title_system_busy", "Sistema Ocupado" },
            { "title_mount_error", "Erro ao Montar" },
            { "title_critical_error", "Erro Crítico" },
            { "msg_busy_operation", "Já existe uma operação em andamento. Aguarde a finalização." },
            { "msg_empty_folder", "A pasta está vazia ou não contém arquivos válidos para proteção." },
            { "msg_cant_mount_busy", "Existe uma operação de criptografia em andamento. Aguarde o término antes de montar unidades virtuais." },
            { "msg_cant_action_busy", "Existe uma operação de criptografia em andamento.\n\nPara evitar corrupção, aguarde a conclusão." },
            { "msg_cant_logout_busy", "Você não pode encerrar a sessão enquanto arquivos estiverem sendo processados." },
            { "msg_cant_reset_busy", "Você não pode restaurar dados enquanto arquivos estiverem sendo processados." },
            { "msg_cant_close_busy", "Existe uma operação em andamento.\n\nPor segurança contra perda de dados, não feche o aplicativo até o término." },
            { "msg_cant_add_busy", "Não é possível adicionar outra pasta enquanto uma criptografia estiver em andamento." },
            { "err_protect_failed", "Erro ao proteger pasta" },
            { "err_restore_failed", "Erro ao restaurar pasta" },
            { "err_folder_mounted_dokan", "Esta pasta está montada como unidade virtual.\n\nDesmonte a unidade antes de protegê-la ou modificar sua criptografia." },
            { "err_insufficient_permissions", "Permissões de gravação insuficientes nesta pasta:\n{0}\n\nVerifique se possui privilégios de administrador." },
            { "err_insufficient_disk_space", "Espaço em disco insuficiente.\n\nSão necessários aproximadamente {0} livres para a criptografia atômica segura, mas há apenas {1} na unidade {2}." },
            { "placeholder_search_vault", "Pesquisar cofre por nome ou caminho..." },
            { "lbl_no_vaults_found", "Nenhum cofre encontrado correspondente à pesquisa." },
            { "lbl_no_vaults_available", "Você ainda não possui nenhum cofre protegido." },
            { "msg_autolock_triggered", "🔒 Sessão bloqueada automaticamente por inatividade." },
            { "prog_pause", "⏸️  PAUSAR" },
            { "prog_resume", "▶️  RETOMAR" },
            { "prog_cancel", "🛑  CANCELAR" },
            { "prog_paused", "⏸️ Operação pausada pelo usuário" },
            { "prog_confirm_cancel", "Deseja cancelar a operação em andamento?\n\nOs arquivos já processados serão mantidos protegidos." },
            { "msg_op_cancelled", "A operação foi cancelada pelo usuário. Os arquivos pendentes não foram alterados." },
        };
        #endregion

        // =============================================================
        // 4. RUSO (RU)
        // =============================================================
        #region DICCIONARIO RUSO (RU)
        private static readonly Dictionary<string, string> RU = new Dictionary<string, string>
        {
            { "menu_protect", "🔒  ЗАЩИТИТЬ" },
            { "menu_unlock", "🔓  ОТКРЫТЬ СЕЙФ" },
            { "menu_files", "📂  МОИ ФАЙЛЫ" },
            { "menu_config", "⚙️ НАСТРОЙКИ" },
            { "menu_manual", "📘  РУКОВОДСТВО" },
            { "menu_exit", "🚪  ВЫХОД" },
            { "title_main", "Центр Безопасности" },
            { "app_subtitle", "Пакет Безопасности" },
            { "tab_restore", "🔓  ВОССТАНОВИТЬ" },
            { "lbl_target", "ЦЕЛЕВАЯ ПАПКА (ВЫБРАТЬ)" },
            { "lbl_pass", "КЛЮЧ ШИФРОВАНИЯ (ПАРОЛЬ)" },
            { "link_forgot", "Забыли пароль?" },
            { "btn_browse", "Обзор..." },
            { "btn_lock", "НАЧАТЬ БЛОКИРОВКУ" },
            { "lbl_path_protected", "ТЕКУЩИЙ ЗАЩИЩЕННЫЙ ПУТЬ" },
            { "btn_decrypt", "РАСШИФРОВАТЬ НАВСЕГДА" },
            { "title_virtual", "Безопасный Виртуальный Доступ" },
            { "lbl_vaults", "МОИ СЕЙФЫ (ВЫБЕРИТЕ ОДИН)" },
            { "lbl_drive", "БУКВА ДИСКА" },
            { "lbl_mount_pass", "КЛЮЧ ШИФРОВАНИЯ (ПАРОЛЬ)" },
            { "btn_mount", "ОТКРЫТЬ ВИРТУАЛЬНЫЙ ДИСК" },
            { "btn_unmount", "ЗАКРЫТЬ ДИСК" },
            { "setup_title", "ДОБРО ПОЖАЛОВАТЬ В LOCKER" },
            { "setup_sub", "Начальная настройка безопасности." },
            { "setup_lbl_create", "СОЗДАЙТЕ МАСТЕР-ПАРОЛЬ" },
            { "setup_lbl_confirm", "ПОДТВЕРДИТЕ ПАРОЛЬ" },
            { "setup_note", "⚠️ Запомните ваше имя пользователя и пароль. Если вы их забудете и не имеете код восстановления,\nваши файлы станут невосстановимыми." },
            { "setup_btn", "УСТАНОВИТЬ ЗАЩИТУ" },
            { "config_title", "НАСТРОЙКИ" },
            { "config_lbl_lang", "IDIOMA" },
            { "config_chk_start", "Запускать с Windows (свернуто)" },
            { "cfg_sec_general", "🌍  ОБЩИЕ" },
            { "cfg_sec_system", "💻  СИСТЕМА" },
            { "cfg_sec_data", "🛡️  КОНФИДЕНЦИАЛЬНОСТЬ" },
            { "cfg_btn_clear", "ОЧИСТИТЬ ИСТОРИЮ" },
            { "cfg_msg_clear", "Вы уверены? Сохраненные пути будут забыты (файлы не удаляются)." },
            { "cfg_msg_reset", "⚠️ Это удалит вашу учетную запись и настройки.\nУбедитесь, что вы расшифровали папки перед удалением.\nПродолжить?" },
            { "cfg_done", "Операция выполнена успешно." },
            { "manual_title", "КРАТКОЕ РУКОВОДСТВО" },
            { "manual_text", "1. ЗАЩИТИТЬ ПАПКУ:\n    - Перейдите на вкладку 'Защитить'.\n    - Выберите папку и введите пароль.\n    - Папка будет скрыта и зашифрована.\n\n2. ДОСТУП К ФАЙЛАМ (ОТКРЫТЬ ХРАНИЛИЩЕ):\n    - Перейдите в 'Открыть Хранилище' в боковом меню.\n    - Выберите папку из списка.\n    - Выберите букву (напр.: M:) и введите пароль.\n    - Она откроется как безопасный виртуальный диск.\n\n3. ВОССТАНОВИТЬ (СНЯТЬ ЗАЩИТУ):\n    - На вкладке 'Защитить' есть опция 'Восстановить'.\n    - Выберите папку для восстановления и введите пароль.\n    - Папка вернется в обычное состояние, будет расшифрована и станет видимой.\n\n4. ⚠️ КРИТИЧЕСКИЕ ПРЕДУПРЕЖДЕНИЯ (ПРОЧИТАТЬ):\n    - НИКОГДА не заходите в скрытую папку для ручной вставки файлов! Они будут повреждены при попытке расшифровки.\n    - Используйте виртуальный диск (Буква: ) для редактирования файлов. Либо расшифруйте папку, создайте, переместите или отредактируйте новые файлы, а затем снова зашифруйте.\n    - НЕ удаляйте файлы 'dir.idx' или 'locker.id', иначе вы потеряете доступ ко всему.\n    - Если вы забудете свой пароль И потеряете код REC, восстановить данные невозможно.\n    - НЕ ВЫКЛЮЧАЙТЕ компьютер во время защиты/восстановления большой папки, это может привести к потере данных." },
            { "msg_select_dir", "Пожалуйста, выберите директорию." },
            { "msg_pass_wrong", "Неверный пароль." },
            { "msg_already_list", "Эта папка уже в вашем списке." },
            { "msg_rec_title", "Умное Восстановление" },
            { "msg_rec_text", "Папка восстановлена!\nЭта папка уже была защищена.\nОна добавлена в список без изменений файлов." },
            { "msg_lock_success", "Папка зашифрована и добавлена в сейф." },
            { "msg_select_restore", "Пожалуйста, выберите папку." },
            { "msg_confirm_decrypt", "Расшифровать папку:\n{0}?" },
            { "msg_decrypt_success", "Папка успешно восстановлена в:" },
            { "msg_mount_select", "Выберите папку из списка." },
            { "msg_mount_select_drive", "Выберите диск" },
            { "err_not_owner", "⛔ ДОСТУП ЗАПРЕЩЕН\nЭта папка принадлежит другому пользователю" },
            { "msg_mount_active", "Эта папка уже открыта на диске {0}" },
            { "msg_drive_busy", "Диск {0} занят. Выберите другой." },
            { "msg_mount_success", "Диск {0} АКТИВЕН.\nВы можете получить доступ через меню 'Мои файлы'." },
            { "msg_unmount_select", "Выберите папку для закрытия." },
            { "msg_unmount_success", "Диск {0} успешно закрыт." },
            { "msg_unmount_error", "Ошибка закрытия. Проверьте открытые файлы." },
            { "msg_no_vault", "Нет открытых сейфов. Сначала подключите один." },
            { "err_drag_folder", "Пожалуйста, перетащите папку, а не файл." },
            { "err_drag_folder_title", "Только Папки" },
            { "err_root", "⚠️ КРИТИЧЕСКАЯ ОШИБКА ⚠️\nВы пытаетесь заблокировать ВЕСЬ ДИСК ({0}).\nЭто повредит данные.\nРЕШЕНИЕ: Создайте папку на диске и выберите её." },
            { "err_self", "⛔ БЛОКИРОВКА ПРЕДОТВРАЩЕНА\nНельзя блокировать папку, где запущена программа." },
            { "err_sys", "⛔ ЗАЩИТА СИСТЕМЫ\nМодификация системных папок Windows запрещена." },
            { "err_security_title", "Операция Прервана" },
            { "status_processing", "⏳ ОБРАБОТКА..." },
            { "status_decrypting", "⏳ РАСШИФРОВКА..." },
            { "tray_working", "Locker - Работает" },
            { "tray_working_desc", "Процесс идет в фоне. Дважды кликните для просмотра." },
            { "tray_done", "Locker - Готово" },
            { "tray_done_lock", "Папка успешно заблокирована." },
            { "tray_done_decrypt", "Папка успешно восстановлена." },
            { "tray_minimized_title", "FolderLocker Активен" },
            { "tray_minimized_msg", "Приложение работает в фоновом режиме." },
            { "tray_menu_open", "Открыть Locker" },
            { "tray_menu_exit", "Выход" },
            { "btn_accept", "ПРИНЯТЬ" },
            { "btn_cancel", "ОТМЕНА" },
            { "btn_yes", "ДА, ПРОДОЛЖИТЬ" },
            { "btn_ready", "ГОТОВО" },
            { "prog_title", "ОБРАБОТКА СЕЙФА..." },
            { "prog_init", "Запуск..." },
            { "prog_hide_btn", "⬇️ Скрыть и работать в фоне" },
            { "prog_file_lbl", "Обработка: {0}" },
            { "prog_done", "Завершение..." },
            { "status_done", "Готово!" },
            { "title_info", "Информация" },
            { "title_confirm", "Подтверждение" },
            { "title_error", "Ошибка" },
            { "title_warning", "Внимание" },
            { "title_success", "Успех" },
            { "title_security", "Безопасность" },
            { "val_min_chars", "Минимум 4 символа." },
            { "val_no_match", "Пароли не совпадают." },
            { "val_save_code", "СОХРАНИТЕ ЭТОТ КОД В БЕЗОПАСНОМ МЕСТЕ:" },
            { "rec_prompt_title", "Восстановление Аккаунта" },
            { "rec_prompt_msg", "Введите Код Восстановления (REC-XXXX):" },
            { "rec_success_msg", "Успех! Ваш пароль:" },
            { "rec_fail_msg", "Неверный или некорректный код." },
            // LOGIN & REGISTER
            { "login_title", "ВХОД" },
            { "login_lbl_user", "ПОЛЬЗОВАТЕЛЬ" },
            { "login_lbl_pass", "ПАРОЛЬ" },
            { "login_btn_enter", "ВОЙТИ" },
            { "login_btn_reg", "Создать новую учетную запись" },
            { "login_err_auth", "Неверное имя пользователя или пароль." },
            { "login_welcome", "Добро пожаловать, {0}!" },

            { "reg_title", "РЕГИСТРАЦИЯ" },
            { "reg_subtitle", "Создать безопасный аккаунт" },
            { "reg_lbl_user", "НОВЫЙ ПОЛЬЗОВАТЕЛЬ" },
            { "reg_lbl_pass", "ПАРОЛЬ" },
            { "reg_btn_create", "СОЗДАТЬ АККАУНТ" },
            { "reg_btn_back", "Назад ко входу" },
            { "reg_err_len", "Логин: Мин 3 симв.\nПароль: Мин 4 симв." },
            { "reg_err_exists", "Пользователь уже существует." },
            { "reg_msg_code", "Аккаунт создан! СОХРАНИТЕ КОД:" },
            { "reg_msg_login", "Регистрация прошла успешно!" },
            { "login_chk_remember", "Запомнить меня" },
            { "msg_logout_confirm", "Выйти из системы?" },
            { "cfg_btn_reset", "⚠️ Excluir Conta" },
            { "btn_exit_user", "Выход ({0})" },
            { "str_0", "Очень слабый" },
            { "str_1", "Слабый" },
            { "str_2", "Нормальный" },
            { "str_3", "Хороший" },
            { "str_4", "Сильный" },
            { "str_5", "Отличный" },
            { "tray_min_title", "FolderLocker Свернут" },
            { "tray_min_click", "Программа свернута, нажмите здесь, чтобы открыть." },
            { "time_less_5s", "Менее 5 секунд" },
            { "time_approx_seconds", "Прибл. {0} сек." },
            { "time_approx_minute", "Прибл. 1 минута" },
            { "time_approx_minutes", "Прибл. {0} мин." },
            { "time_approx_hours_mins", "Прибл. {0}ч {1}м" },
            { "prescan_title_warning", "⚠️ Внимание: Большой объем файлов" },
            { "prescan_title_summary", "🛡️ Сводка безопасности" },
            { "prescan_lbl_files", "ФАЙЛЫ" },
            { "prescan_lbl_size", "ОБЩИЙ РАЗМЕР" },
            { "prescan_lbl_time", "РАСЧ. ВРЕМЯ" },
            { "prescan_large_warning", "⚠️ Внимание: Обнаружен большой объем. Шифрование выполняется транзакционными пакетами (Two-Phase Commit) для исключения потерь данных." },
            { "prescan_normal_summary", "🛡️ Максимальная безопасность: Папка будет защищена военным шифрованием AES-256 CTR с контролем целостности." },
            { "prescan_junk_info", "\n🧹 Умный фильтр: Исключено {0:N0} временных файлов (thumbs.db, .tmp и др.)." },
            { "prescan_prompt", "Вы хотите начать шифрование прямо сейчас?" },
            { "prescan_btn_proceed", "🔒 НАЧАТЬ ШИФРОВАНИЕ" },
            { "cfg_sub", "Управление языком, автозапуском системы и локальной криптографической базой." },
            { "cfg_badge_system", "⚙ СИСТЕМНЫЕ НАСТРОЙКИ" },
            { "cfg_badge_security", "🔒 ЛОКАЛЬНАЯ БЕЗОПАСНОСТЬ" },
            { "cfg_startup_title", "Запуск вместе с Windows" },
            { "cfg_startup_sub", "Запускать FolderLocker в свернутом виде в системном трее при загрузке ПК." },
            { "cfg_junk_title", "Фильтр временных и мусорных файлов" },
            { "cfg_junk_sub", "Пропускать и очищать thumbs.db, desktop.ini, .tmp и временные блокировки." },
            { "cfg_autolock_title", "Автоблокировка при неактивности" },
            { "cfg_autolock_sub", "Блокировать сессию и отмонтировать диски при простое." },
            { "opt_autolock_disabled", "Отключено" },
            { "opt_autolock_1min", "1 минута (Тест)" },
            { "opt_autolock_3min", "3 минуты" },
            { "opt_autolock_5min", "5 минут (Рекомендуется)" },
            { "opt_autolock_10min", "10 минут" },
            { "opt_autolock_15min", "15 минут" },
            { "opt_autolock_30min", "30 минут" },
            { "cfg_danger_title", "Сброс к заводским настройкам" },
            { "cfg_danger_sub", "Удаляет базу пользователей и сбрасывает программу к начальному состоянию." },
            { "cfg_btn_reset_label", "СБРОСИТЬ" },
            { "cfg_sec_dev", "О ПРОГРАММЕ И АВТОРАХ" },
            { "cfg_dev_sub", "Разработано на базе Dokan и AES-256 CTR • Атомарная архитектура шифрования" },
            { "cfg_btn_credits_label", "АВТОРЫ" },
            { "cfg_footer_label", "FolderLocker Security Suite • Сборка 2026.1 • Криптографический комплекс" },
            { "sub_virtual_mount", "Монтируйте защищенные хранилища как виртуальные диски на лету без расшифровки." },
            { "tip_virtual_mount", "💡 Виртуальный диск появится в Проводнике и шифруется на лету в реальном времени." },
            { "count_vaults_zero", "0 ХРАНИЛИЩ" },
            { "count_vaults_one", "1 ХРАНИЛИЩЕ" },
            { "count_vaults_many", "{0} ХРАНИЛИЩ" },
            { "count_vaults_found", "{0}/{1} НАЙДЕНО" },
            { "lbl_drop_hint", "(Перетащите папку сюда или выберите)" },
            { "lbl_pass_hint", "🛡️ Ключи создаются локально. Пароль никогда не сохраняется в открытом виде." },
            { "lbl_guarantee_atomic", "⚡ Атомарная защита: Транзакционные операции без риска повреждения файлов." },
            { "lbl_guarantee_decrypt", "⚡ Безопасная расшифровка: Файлы и папки будут полностью восстановлены в исходном виде." },
            { "manual_sub", "Узнайте, как шифровать папки, монтировать виртуальные диски и защищать данные." },
            { "manual_badge_guide", "📖 РУКОВОДСТВО" },
            { "manual_badge_practices", "🛡 ЛУЧШИЕ ПРАКТИКИ" },
            { "man_card1_title", "1. КАК ЗАЩИТИТЬ ПАПКУ" },
            { "man_card1_step1", "• Перейдите на вкладку 'Защитить' в Центре безопасности." },
            { "man_card1_step2", "• Выберите папку через кнопку 'Обзор...' или перетащите её в окно." },
            { "man_card1_step3", "• Введите мастер-пароль и нажмите 'Начать блокировку'. Ваши файлы будут зашифрованы надежным алгоритмом AES-256 CTR." },
            { "man_card2_title", "2. ДОСТУП К ФАЙЛАМ (ОТКРЫТЬ ХРАНИЛИЩЕ)" },
            { "man_card2_step1", "• Перейдите в раздел 'Открыть хранилище' в левом боковом меню." },
            { "man_card2_step2", "• Выберите зашифрованную папку и назначьте букву виртуального диска (напр. M:)." },
            { "man_card2_step3", "• Введите пароль. Хранилище подключится как виртуальный диск в Проводнике для работы на лету без расшифровки." },
            { "man_card3_title", "3. ВОССТАНОВЛЕНИЕ (СНЯТИЕ ЗАЩИТЫ)" },
            { "man_card3_step1", "• В Центре безопасности перейдите на вкладку 'Восстановить'." },
            { "man_card3_step2", "• Выберите защищенную папку из списка и нажмите 'Восстановить и расшифровать'." },
            { "man_card3_step3", "• Папка вернется в обычное состояние, а все файлы будут полностью расшифрованы." },
            { "man_card4_title", "4. КРИТИЧЕСКИЕ ПРЕДУПРЕЖДЕНИЯ (ОБЯЗАТЕЛЬНО К ПРОЧТЕНИЮ)" },
            { "man_card4_step1", "⚠️ НИКОГДА не заходите в скрытую папку для ручного копирования или изменения файлов! Они будут повреждены." },
            { "man_card4_step2", "⚠️ Всегда используйте виртуальный диск (букву диска) для безопасной и прозрачной работы с файлами." },
            { "man_card4_step3", "⚠️ НЕ удаляйте файлы 'dir.idx' и 'locker.id'; они содержат карты шифрования, без которых доступ будет утерян." },
            { "man_card4_step4", "⚠️ Сохраните REC-код в надежном месте. Без пароля и REC-кода восстановить данные математически невозможно." },
            { "man_card4_step5", "⚠️ НЕ выключайте компьютер и не извлекайте диск во время операций шифрования или расшифровки." },
            { "cred_badge_dev", "👨‍💻 РАЗРАБОТЧИК" },
            { "cred_badge_suite", "🚀 FOLDERLOCKER SUITE" },
            { "cred_title", "ОБ АВТОРЕ И РАЗРАБОТКЕ" },
            { "cred_author_info", "David Armando Platas\nВедущий инженер и архитектор безопасности\n\nКонтакты: davarman10@gmail.com" },
            { "cred_desc", "FolderLocker Security Suite • 2026\nСоздано на C#, .NET 8, Dokan Mirror Driver и атомарном AES-256 CTR." },
            { "cred_btn_github", "🌐 Открыть GitHub" },
            { "cred_btn_back", "⬅ Назад к настройкам" },
            { "login_err_user_first", "Сначала введите имя пользователя." },
            { "login_branding_desc", "Военный класс безопасности AES-256 CTR\nПрозрачный доступ через виртуальный диск Dokan\nАрхитектура с нулевым разглашением" },
            { "setup_err_empty", "Пароль не может быть пустым." },
            { "setup_err_match", "Пароли не совпадают." },
            { "title_welcome", "Добро пожаловать" },
            { "title_busy", "Выполняется операция" },
            { "title_empty_folder", "Пустая папка" },
            { "title_security_validation", "Проверка безопасности" },
            { "title_restore_validation", "Проверка восстановления" },
            { "title_confirm_cancel", "Подтверждение отмены" },
            { "title_system_busy", "Система занята" },
            { "title_mount_error", "Ошибка монтирования" },
            { "title_critical_error", "Критическая ошибка" },
            { "msg_busy_operation", "Операция шифрования уже выполняется. Пожалуйста, дождитесь ее окончания." },
            { "msg_empty_folder", "Папка пуста или не содержит файлов, доступных для защиты." },
            { "msg_cant_mount_busy", "В данный момент выполняется шифрование. В целях безопасности дождитесь окончания перед монтированием дисков." },
            { "msg_cant_action_busy", "Выполняется шифрование или расшифровка.\n\nВо избежание повреждения файлов дождитесь завершения." },
            { "msg_cant_logout_busy", "Нельзя выйти из системы во время обработки файлов." },
            { "msg_cant_reset_busy", "Нельзя сбросить базу данных во время обработки файлов." },
            { "msg_cant_close_busy", "Выполняется операция.\n\nВо избежание потери данных нельзя закрыть приложение до ее завершения." },
            { "msg_cant_add_busy", "Нельзя добавить другую папку, пока выполняется шифрование." },
            { "err_protect_failed", "Ошибка защиты папки" },
            { "err_restore_failed", "Ошибка восстановления" },
            { "err_folder_mounted_dokan", "Эта папка в данный момент смонтирована как виртуальный диск.\n\nПожалуйста, отмонтируйте её перед изменением шифрования." },
            { "err_insufficient_permissions", "Недостаточно прав для записи в данную папку:\n{0}\n\nУбедитесь, что у вас есть права администратора и файлы не заблокированы." },
            { "err_insufficient_disk_space", "Недостаточно свободного места на диске.\n\nТребуется около {0} для атомарного шифрования (Two-Phase Commit), но на диске {2} доступно только {1}." },
            { "placeholder_search_vault", "Поиск хранилища по названию или пути..." },
            { "lbl_no_vaults_found", "Хранилищ по вашему запросу не найдено." },
            { "lbl_no_vaults_available", "У вас пока нет защищенных хранилищ." },
            { "msg_autolock_triggered", "🔒 Сессия заблокирована из-за неактивности." },
            { "prog_pause", "⏸️  ПАУЗА" },
            { "prog_resume", "▶️  ПРОДОЛЖИТЬ" },
            { "prog_cancel", "🛑  ОТМЕНА" },
            { "prog_paused", "⏸️ Операция приостановлена пользователем" },
            { "prog_confirm_cancel", "Отменить текущую операцию?\n\nУже обработанные файлы останутся защищенными." },
            { "msg_op_cancelled", "Операция отменена пользователем. Оставшиеся файлы не изменены." },
        };
        #endregion

        // =============================================================
        // 5. CHINO MANDARÍN (ZH)
        // =============================================================
        #region DICCIONARIO CHINO (CN)
        private static readonly Dictionary<string, string> CN = new Dictionary<string, string>
        {
            { "menu_protect", "🔒  保护文件夹" },
            { "menu_unlock", "🔓  打开保险库" },
            { "menu_files", "📂  我的文件" },
            { "menu_config", "⚙️ 设置" },
            { "menu_manual", "📘  用户手册" },
            { "menu_exit", "🚪  退出" },
            { "title_main", "安全中心" },
            { "app_subtitle", "安全套件" },
            { "tab_restore", "🔓  恢复" },
            { "lbl_target", "目标文件夹（选择目录）" },
            { "lbl_pass", "加密密钥（密码）" },
            { "link_forgot", "忘记密码？" },
            { "btn_browse", "浏览..." },
            { "btn_lock", "开始锁定" },
            { "lbl_path_protected", "当前受保护路径" },
            { "btn_decrypt", "永久解密" },
            { "title_virtual", "安全虚拟访问" },
            { "lbl_vaults", "我的保险库（选择一个）" },
            { "lbl_drive", "驱动器号" },
            { "lbl_mount_pass", "加密密钥（密码）" },
            { "btn_mount", "打开虚拟驱动器" },
            { "btn_unmount", "关闭驱动器" },
            { "setup_title", "欢迎使用 文件夹锁" },
            { "setup_sub", "初始安全设置。" },
            { "setup_lbl_create", "创建主密码" },
            { "setup_lbl_confirm", "确认密码" },
            { "setup_note", "⚠️ 请记住您的用户名和密码。如果您忘记了且没有恢复代码,\n您的文件将无法恢复。" },
            { "setup_btn", "建立安全" },
            { "config_title", "设置" },
            { "config_lbl_lang", "语言" },
            { "config_chk_start", "随 Windows 启动（最小化）" },
            { "cfg_sec_general", "🌍  常规" },
            { "cfg_sec_system", "💻  系统" },
            { "cfg_sec_data", "🛡️  隐私与数据" },
            { "cfg_btn_clear", "清除路径历史" },
            { "cfg_msg_clear", "确定吗？保存的文件夹位置将被遗忘（文件不会被删除）。" },
            { "cfg_msg_reset", "⚠️ 这将删除您的账户和配置。\n请确保在删除前已解密您的文件夹。\n是否继续?" },
            { "cfg_done", "操作成功完成。" },
            { "manual_title", "快速用户指南" },
            { "manual_text", "1. 保护文件夹:\n    - 转到“保护”选项卡。\n    - 选择一个文件夹并输入您的密码。\n    - 该文件夹将被隐藏和加密。\n\n2. 访问文件 (打开保险库):\n    - 转到侧边菜单中的“打开保险库”。\n    - 从列表中选择您的文件夹。\n    - 选择一个盘符 (例如：M:) 并输入您的密码。\n    - 它将以安全虚拟驱动器的形式打开。\n\n3. 恢复 (移除保护):\n    - “保护”选项卡内有“恢复”选项。\n    - 选择要恢复的文件夹并输入您的密码。\n    - 该文件夹将恢复正常，它将被解密并可见。\n\n4. ⚠️ 关键警告 (必读):\n    - 切勿手动进入隐藏文件夹粘贴文件！否则在尝试解密时会被损坏。\n    - 使用虚拟驱动器（盘符：）编辑您的文件。 或者，解密文件夹，创建、移动或编辑新文件，然后重新加密。\n    - 请勿删除 'dir.idx' 或 'locker.id' 文件，否则您将失去所有访问权限。\n    - 如果您忘记了密码并且丢失了恢复代码 (REC)，则无法恢复您的数据。\n    - 在保护/恢复大文件夹期间，请勿关闭计算机，否则可能导致数据丢失。" },
            { "msg_select_dir", "请选择一个目录。" },
            { "msg_pass_wrong", "密码错误。" },
            { "msg_already_list", "此文件夹已在您的列表中。" },
            { "msg_rec_title", "智能恢复" },
            { "msg_rec_text", "文件夹已恢复！\n此文件夹已受保护。\n已添加到您的列表，未修改文件。" },
            { "msg_lock_success", "文件夹已加密并添加到保险库。" },
            { "msg_select_restore", "请选择一个文件夹。" },
            { "msg_confirm_decrypt", "解密文件夹：\n{0}？" },
            { "msg_decrypt_success", "文件夹成功恢复至：" },
            { "msg_mount_select", "从列表中选择一个文件夹。" },
            { "msg_mount_select_drive", "选择驱动器" },
            { "err_not_owner", "⛔ 访问被拒绝\n此文件夹属于其他用户" },
            { "msg_mount_active", "此文件夹已在驱动器 {0} 上打开" },
            { "msg_drive_busy", "驱动器 {0} 忙。请选择另一个。" },
            { "msg_mount_success", "驱动器 {0} 已激活。\n您可以通过“我的文件”菜单访问。" },
            { "msg_unmount_select", "在列表中选择要关闭的文件夹。" },
            { "msg_unmount_success", "驱动器 {0} 已成功关闭。" },
            { "msg_unmount_error", "卸载时出错。请检查是否有打开的文件。" },
            { "msg_no_vault", "未找到打开的保险库。请先挂载一个。" },
            { "err_drag_folder", "请拖动文件夹，而不是单个文件。" },
            { "err_drag_folder_title", "仅限文件夹" },
            { "err_root", "⚠️ 严重错误 ⚠️\n您试图锁定整个驱动器 ({0})。\n这会损坏驱动器。\n解决方案：在驱动器内创建一个文件夹并选择它。" },
            { "err_self", "⛔ 自动锁定已阻止\n您无法锁定此程序正在运行的文件夹。" },
            { "err_sys", "⛔ 系统保护\n不允许修改 Windows 系统文件夹。" },
            { "err_security_title", "操作因安全原因中止" },
            { "status_processing", "⏳ 处理中..." },
            { "status_decrypting", "⏳ 解密中..." },
            { "tray_working", "Locker - 正在工作" },
            { "tray_working_desc", "进程在后台运行。双击此处查看进度。" },
            { "tray_done", "Locker - 完成" },
            { "tray_done_lock", "文件夹已成功锁定。" },
            { "tray_done_decrypt", "文件夹已成功恢复。" },
            { "tray_minimized_title", "FolderLocker 活动" },
            { "tray_minimized_msg", "应用程序正在后台运行。" },
            { "tray_menu_open", "打开 Locker" },
            { "tray_menu_exit", "退出" },
            { "btn_accept", "接受" },
            { "btn_cancel", "取消" },
            { "btn_yes", "是，继续" },
            { "btn_ready", "完成" },
            { "prog_title", "正在处理保险库..." },
            { "prog_init", "正在启动..." },
            { "prog_hide_btn", "⬇️ 隐藏并在后台工作" },
            { "prog_file_lbl", "正在处理：{0}" },
            { "prog_done", "正在完成..." },
            { "status_done", "完成！" },
            { "title_info", "信息" },
            { "title_confirm", "确认" },
            { "title_error", "错误" },
            { "title_warning", "警告" },
            { "title_success", "成功" },
            { "title_security", "安全" },
            { "val_min_chars", "最少 4 个字符。" },
            { "val_no_match", "密码不匹配。" },
            { "val_save_code", "请将此代码保存在安全的地方：" },
            { "rec_prompt_title", "账户恢复" },
            { "rec_prompt_msg", "输入恢复代码 (REC-XXXX)：" },
            { "rec_success_msg", "成功！您的密码是：" },
            { "rec_fail_msg", "代码无效或不正确。" },
            // LOGIN & REGISTER
            { "login_title", "登录" },
            { "login_lbl_user", "用户名" },
            { "login_lbl_pass", "密码" },
            { "login_btn_enter", "登录" },
            { "login_btn_reg", "创建新账户" },
            { "login_err_auth", "用户名或密码错误。" },
            { "login_welcome", "欢迎，{0}！" },

            { "reg_title", "注册" },
            { "reg_subtitle", "创建一个新的安全账户" },
            { "reg_lbl_user", "新用户名" },
            { "reg_lbl_pass", "密码" },
            { "reg_btn_create", "创建账户" },
            { "reg_btn_back", "返回登录" },
            { "reg_err_len", "用户：最少3个字符。\n密码：最少4个字符。" },
            { "reg_err_exists", "用户名已存在。" },
            { "reg_msg_code", "账户已创建！保存您的代码：" },
            { "reg_msg_login", "注册成功!" },
            { "login_chk_remember", "记住用户" },
            { "msg_logout_confirm", "退出当前会话？" },
            { "cfg_btn_reset", "⚠️ 删除账户" },
            { "btn_exit_user", "退出 ({0})" },
            { "str_0", "非常弱" },
            { "str_1", "弱" },
            { "str_2", "中等" },
            { "str_3", "好" },
            { "str_4", "强" },
            { "str_5", "优秀" },
            { "tray_min_title", "FolderLocker 已最小化" },
            { "tray_min_click", "程序已最小化，点击此处打开。" },
            { "time_less_5s", "少于 5 秒" },
            { "time_approx_seconds", "约 {0} 秒" },
            { "time_approx_minute", "约 1 分钟" },
            { "time_approx_minutes", "约 {0} 分钟" },
            { "time_approx_hours_mins", "约 {0}小时 {1}分" },
            { "prescan_title_warning", "⚠️ 警告：检测到大容量文件" },
            { "prescan_title_summary", "🛡️ 安全摘要" },
            { "prescan_lbl_files", "文件数量" },
            { "prescan_lbl_size", "总大小" },
            { "prescan_lbl_time", "预估时间" },
            { "prescan_large_warning", "⚠️ 提示：检测到大量文件。加密过程将通过事务性批处理（两阶段提交）执行，确保零数据丢失。" },
            { "prescan_normal_summary", "🛡️ 顶级安全：文件夹将通过军工级 AES-256 CTR 算法加密并进行完整性验证。" },
            { "prescan_junk_info", "\n🧹 智能过滤：已自动排除 {0:N0} 个临时/锁定文件（如 thumbs.db、.tmp 等）。" },
            { "prescan_prompt", "您希望现在开始加密吗？" },
            { "prescan_btn_proceed", "🔒 开始加密" },
            { "cfg_sub", "管理应用程序语言、系统开机自启和本地加密数据库。" },
            { "cfg_badge_system", "⚙ 系统首选项" },
            { "cfg_badge_security", "🔒 本地安全" },
            { "cfg_startup_title", "随 Windows 开机启动" },
            { "cfg_startup_sub", "开机时在系统托盘后台静默启动 FolderLocker。" },
            { "cfg_junk_title", "垃圾/临时文件智能过滤" },
            { "cfg_junk_sub", "自动跳过并清理 thumbs.db、desktop.ini、.tmp 及临时占用文件。" },
            { "cfg_autolock_title", "闲置自动锁定" },
            { "cfg_autolock_sub", "闲置一定时间后自动锁定会话并安全卸载虚拟驱动器。" },
            { "opt_autolock_disabled", "已禁用" },
            { "opt_autolock_1min", "1 分钟 (测试)" },
            { "opt_autolock_3min", "3 分钟" },
            { "opt_autolock_5min", "5 分钟 (推荐)" },
            { "opt_autolock_10min", "10 分钟" },
            { "opt_autolock_15min", "15 分钟" },
            { "opt_autolock_30min", "30 分钟" },
            { "cfg_danger_title", "恢复出厂设置" },
            { "cfg_danger_sub", "删除本地用户数据库并将套件重置为初始状态。" },
            { "cfg_btn_reset_label", "重置" },
            { "cfg_sec_dev", "关于与开发人员" },
            { "cfg_dev_sub", "基于 Dokan 与 AES-256 CTR 开发 • 原子级加密架构" },
            { "cfg_btn_credits_label", "开发人员" },
            { "cfg_footer_label", "FolderLocker Security Suite • Build 2026.1 • 安全密码学套件" },
            { "sub_virtual_mount", "将受保护的保管库动态挂载为虚拟硬盘，无需解密。" },
            { "tip_virtual_mount", "💡 虚拟驱动器将显示在“此电脑”中，并在后台实时透明加密。" },
            { "count_vaults_zero", "0 个保管库" },
            { "count_vaults_one", "1 个保管库" },
            { "count_vaults_many", "{0} 个保管库" },
            { "count_vaults_found", "找到 {0}/{1} 个" },
            { "lbl_drop_hint", "(拖放文件夹到此处或浏览)" },
            { "lbl_pass_hint", "🛡️ 密钥在本地生成。您的密码绝不会以明文形式存储。" },
            { "lbl_guarantee_atomic", "⚡ 原子保护：事务性操作，防止断电或意外造成文件损坏。" },
            { "lbl_guarantee_decrypt", "⚡ 安全解密：文件和子目录将完全恢复为原始格式，零数据丢失。" },
            { "manual_sub", "了解如何加密文件夹、挂载虚拟磁盘以及保护您的隐私数据。" },
            { "manual_badge_guide", "📖 用户指南" },
            { "manual_badge_practices", "🛡 最佳实践" },
            { "man_card1_title", "1. 如何保护文件夹" },
            { "man_card1_step1", "• 前往安全中心中的“保护”选项卡。" },
            { "man_card1_step2", "• 使用“浏览...”按钮选择您的文件夹，或直接拖放到窗口中。" },
            { "man_card1_step3", "• 输入主密码并点击“开始锁定”。您的文件将使用军工级 AES-256 CTR 和两阶段提交保护。" },
            { "man_card2_title", "2. 访问文件（打开保管库）" },
            { "man_card2_step1", "• 在左侧菜单中进入“打开保管库”选项。" },
            { "man_card2_step2", "• 选择已加密的文件夹并指定虚拟驱动器盘符（例如 M:）。" },
            { "man_card2_step3", "• 输入主密码。保管库将在“此电脑”中挂载为虚拟磁盘，可直接实时编辑文件而无需解密。" },
            { "man_card3_title", "3. 还原（移除保护）" },
            { "man_card3_step1", "• 在安全中心中，切换到顶部的“还原”选项卡。" },
            { "man_card3_step2", "• 从列表中选择受保护的文件夹，并点击“还原与解密”。" },
            { "man_card3_step3", "• 文件夹将恢复为正常的可见状态，所有文件将完全解密且保持原貌。" },
            { "man_card4_title", "4. 关键安全警告（必读）" },
            { "man_card4_step1", "⚠️ 严禁手动进入隐藏文件夹粘贴或修改文件！否则解密时将导致数据损坏。" },
            { "man_card4_step2", "⚠️ 请始终使用虚拟驱动器（盘符）安全透明地编辑和查看您的文件。" },
            { "man_card4_step3", "⚠️ 切勿删除 'dir.idx' 或 'locker.id' 文件；它们包含访问保管库所需的关键加密索引。" },
            { "man_card4_step4", "⚠️ 请妥善保管您的 REC 恢复码。若同时遗失密码与恢复码，数据在数学上将不可恢复。" },
            { "man_card4_step5", "⚠️ 在对大量文件执行加密或还原操作期间，请勿关机或拔出外置存储设备。" },
            { "cred_badge_dev", "👨‍💻 开发者" },
            { "cred_badge_suite", "🚀 FOLDERLOCKER 密码套件" },
            { "cred_title", "开发团队与鸣谢" },
            { "cred_author_info", "David Armando Platas\n首席软件工程师兼安全架构师\n\n联系方式：davarman10@gmail.com" },
            { "cred_desc", "FolderLocker Security Suite v5.2 • 2026\n基于 C#、.NET 8、Dokan 驱动与原子级 AES-256 CTR 构建。" },
            { "cred_btn_github", "🌐 访问 GitHub" },
            { "cred_btn_back", "⬅ 返回设置" },
            { "login_err_user_first", "请先输入用户名。" },
            { "login_branding_desc", "军工级 AES-256 CTR 强加密\n基于 Dokan 虚拟驱动器的透明访问\n真正的零知识加密架构" },
            { "setup_err_empty", "密码不能为空。" },
            { "setup_err_match", "两次输入的密码不一致。" },
            { "title_welcome", "欢迎" },
            { "title_busy", "操作进行中" },
            { "title_empty_folder", "文件夹为空" },
            { "title_security_validation", "安全验证" },
            { "title_restore_validation", "还原验证" },
            { "title_confirm_cancel", "确认取消" },
            { "title_system_busy", "系统忙碌" },
            { "title_mount_error", "挂载失败" },
            { "title_critical_error", "严重错误" },
            { "msg_busy_operation", "加密或解密操作正在进行中，请等待其完成。" },
            { "msg_empty_folder", "该文件夹为空或不包含可保护的有效文件。" },
            { "msg_cant_mount_busy", "系统正在进行加密操作。为确保安全，请等待其完成后再挂载虚拟驱动器。" },
            { "msg_cant_action_busy", "正在进行加密或解密操作。\n\n为避免文件损坏，请等待其完成。" },
            { "msg_cant_logout_busy", "文件正在处理中，此时无法注销登录。" },
            { "msg_cant_reset_busy", "文件正在处理中，无法执行重置操作。" },
            { "msg_cant_close_busy", "操作正在进行中。\n\n为防数据损坏或丢失，在操作完成前无法关闭程序。" },
            { "msg_cant_add_busy", "当前正在加密，无法添加其他文件夹。" },
            { "err_protect_failed", "保护文件夹失败" },
            { "err_restore_failed", "还原文件夹失败" },
            { "err_folder_mounted_dokan", "该文件夹当前已被挂载为虚拟磁盘。\n\n在修改其加密状态前，请先卸载虚拟驱动器。" },
            { "err_insufficient_permissions", "您对此文件夹没有足够的写入权限：\n{0}\n\n请确保拥有管理员权限且文件未被占用。" },
            { "err_insufficient_disk_space", "磁盘空间不足。\n\n安全的两阶段原子加密大约需要 {0} 剩余空间，但驱动器 {2} 仅有 {1} 可用。" },
            { "placeholder_search_vault", "按名称或路径搜索保管库..." },
            { "lbl_no_vaults_found", "未找到符合搜索条件的保管库。" },
            { "lbl_no_vaults_available", "您目前没有任何受保护的保管库。" },
            { "msg_autolock_triggered", "🔒 因长时间闲置，会话已自动锁定。" },
            { "prog_pause", "⏸️  暂停" },
            { "prog_resume", "▶️  继续" },
            { "prog_cancel", "🛑  取消" },
            { "prog_paused", "⏸️ 用户已暂停操作" },
            { "prog_confirm_cancel", "确定要取消当前操作吗？\n\n已完成处理的文件将保持受保护状态。" },
            { "msg_op_cancelled", "操作已被用户取消。待处理的文件未作任何更改。" },
        };
        #endregion

        // Método inteligente que selecciona el diccionario correcto
        public static string Get(string key)
        {
            Dictionary<string, string> dict;

            switch (CurrentLang)
            {
                case "CN": dict = CN; break;
                case "PT": dict = PT; break;
                case "RU": dict = RU; break;
                case "EN": dict = EN; break;
                default: dict = ES; break;
            }

            if (dict != null && dict.TryGetValue(key, out var val)) return val;
            if (ES.TryGetValue(key, out var esVal)) return esVal;
            return key;
        }
    }
}